/* ===== English Strings ===== */
I18n.register('en', {
// Title
'splash.loading': 'Loading worms...',
'title.tagline': 'A Management RPG About Life in a Funeral House',
'title.quote': '"You don\'t save lives. You help end them... professionally."',
'title.new_game': 'NEW GAME', 'title.continue': 'LOAD GAME', 'title.resume': 'RESUME', 'title.credits': 'CREDITS',
'title.save': 'SAVE', 'title.exit': 'EXIT',
'title.exit_confirm': 'Are you sure you want to exit? Unsaved progress will be lost.',
'title.footer': 'GAME DESIGN & CONCEPT BY K. ARLÓN<br>DARK HUMOR CONTENT — RATED BY DEATH INC.',
'credits.title': '♱ CREDITS',
'credits.desc': 'A game about death, paperwork, and terrible coffee.',
'credits.design': 'Game Design & Concept: K. Arlón',
'credits.orator': 'Orator: Iván (he insisted)',
'credits.quote': '"Life is temporary. Paperwork is eternal."',
'credits.back': 'BACK',
// Name
'name.title': 'WHO DARES RUN A FUNERAL HOME?', 'name.subtitle': 'Enter your name, future undertaker:',
'name.placeholder': 'Your name...', 'name.begin': 'BEGIN YOUR CAREER',
'name.error': 'Enter a name! Even the dead have names.',
'name.f1': '"Every great mortician started somewhere."', 'name.f2': '"Death is just the beginning... of your career."',
'name.f3': '"Your mother must be so proud."', 'name.f4': '"Hopefully you spell it right on the tombstones."',
'name.f5': '"The dead can\'t judge your name. The living will."',
// Welcome
'welcome.title': 'WELCOME TO THANATOPRACTOR',
'welcome.p1': 'Here we don\'t save lives, we just tie them up with a bow. Your job is simple: make up the dead so they look alive, burn them if the family doesn\'t want to see them anymore, and above all, don\'t get fond of necrophilia.',
'welcome.p2': 'By clicking below, you accept that formaldehyde is your new favorite cologne, that ghosts don\'t pay rent, and that we are not responsible for recurring nightmares or the sudden loss of your own soul.',
'welcome.accept': 'I ACCEPT THE TERMS',
// Hub
'hub.day': 'Day', 'hub.reputation': 'REPUTATION', 'hub.schedule': "TODAY'S SCHEDULE",
'hub.no_appointments': 'No appointments yet...', 'hub.eternal_rest': 'ETERNAL REST',
'hub.funeral_house': 'FUNERAL HOUSE', 'hub.motto': '"We care to the end"',
'hub.welcome': '☠ Welcome, {0}. The dead await.',
'hub.locked': '🔒 Unlock this improvement in the Upgrades menu!',
// Nav
'nav.reception': 'Reception', 'nav.embalming': 'Embalming', 'nav.cafeteria': 'Cafeteria',
'nav.crematorium': 'Cremator.', 'nav.viewing': 'Viewing', 'nav.chapel': 'Chapel',
'nav.upgrades': 'Upgrades', 'nav.families': 'Families',
// Reception
'rec.title': 'RECEPTION', 'rec.new_arrival': 'NEW ARRIVAL', 'rec.phone': 'PHONE CALL',
'rec.paperwork': 'PAPERWORK', 'rec.upgrades': 'UPGRADES',
'rec.appointments': "TODAY'S APPOINTMENTS", 'rec.no_appointments': 'No appointments today',
'rec.no_waiting': 'No families are waiting right now.',
'rec.phone_title': '📞 PHONE MENU', 'rec.phone_subtitle': 'Who would you like to call today?',
'rec.job_interview': 'Job Interview ($50)', 'rec.job_result': 'You called a candidate. They heard screaming in the background and hung up.',
'rec.order_hearse': 'Order Hearse ($150)', 'rec.hearse_ordered': 'Hearse ordered. The driver says he\'ll be there "eventually".',
'rec.hearse_multi': 'Hearse(s) ordered. Expect them in 1 hour.',
'rec.need_money_hearse': 'Need ${0} for {1} hearses!',
'rec.order_flowers': 'Order Flowers ($50)', 'rec.flowers_result': 'Fresh flowers delivered! The viewing room smells slightly less like formaldehyde.',
'rec.nevermind': 'Nevermind',
'rec.personal_pickup': 'Personal hearse pickup for {0} at {1}',
'rec.personal_hearse': '🚗 Use Personal Hearse (Free)',
'rec.niece_car': '🚗 Use Niece\'s Car (Free)',
'rec.car_cooldown': '🚗 Car on cooldown ({0}h)',
'rec.car_dispatched': '🚗 Car dispatched for {0}. It will be away for {1}h.',
'rec.niece_arrived': '🚗 Your niece arrived instantly! {0}\'s family has departed.',
'rec.car_busy': 'The car is currently out doing a transfer!',
'rec.no_family_transport': 'No families waiting for transport.',
'rec.no_paperwork': '📝 No paperwork right now. Enjoy the quiet.',
'rec.pw_title': '📝 PAPERWORK', 'rec.pw_roll': 'Roll D20',
'rec.pw_success': 'Success! You earned ${0}.', 'rec.pw_fail': 'Failure! You lost ${0}.',
'rec.pw_discarded': '📝 Paperwork discarded.', 'rec.pw_decline': '(Decline)',
'rec.pw_dc': 'Difficulty: {0}',
'rec.niece_desc': 'Your niece is waiting with her car in the parking lot!',
'eng.paperwork_success': 'Paperwork success',
'eng.paperwork_failed': 'Paperwork failure',
'eng.new_pw': 'New Paperwork at {0}',
'eng.not_enough': 'Not enough money!',
'eng.job_call': 'Call related to job',
'eng.ordered_flowers': 'Ordered flowers',
'eng.ordered_hearse': 'Ordered hearse',
'eng.level_bonus': 'Rank Promotion Bonus',
'eng.arrival_desc': 'New arrival at {0}',
'rec.hearse_picking': 'Hearse transfer for {0} at {1}',
'rec.car_ordered': '📦 (Car ordered en route) - {0}',
// Paperwork Tasks
'pw_florist': 'Try to pay the florist less money than the actual bill.',
'pw_ivan': "Bill speaker Ivan's expenses to the insurance company.",
'pw_niece': "Use your niece's car as a hearse to save money.",
'pw_cleaning': 'Hire a cleaning crew that looks suspiciously underage.',
'pw_sign': 'Sign all the papers on the desk without reading them.',
'pw_formal': 'Convince the formaldehyde supplier you already paid last month.',
'pw_urn': 'Sell the most expensive urn by claiming it is gold-plated.',
'pw_teeth': "Extract gold teeth from the incinerator 'for recycling'.",
'pw_gin': 'Water down the formaldehyde chemicals with cheap gin.',
'pw_charity': "Donate to the 'Widows of Fallen Morticians' charity.",
'pw_weekend': "Organize a 'bring your own body' discount weekend.",
'pw_mourner': "Hire a professional 'hyper-mourner' to boost the atmosphere.",
'pw_outfits': "Recycle the 'single-use' funeral outfits from last week.",
'pw_ghosts': 'Convince a family that ghosts are actually "premium features".',
'pw_used_coffin': 'Sell a "slightly used" coffin to a nearsighted family.',
'pw_gym': "Forge the deceased's signature to cancel their gym membership.",
'pw_reggaeton': 'Convince the priest that "Ave Maria" sounds better in reggaeton.',
'pw_scare': 'Charge extra for "ghost-scaring" by waving a flashlight in the basement.',
'pw_celestial': 'Sell "Celestial Music" (a broken speaker) to a deaf client.',
'pw_ivan_support': 'Register Ivan as "Emotional Support Animal" for tax deductions.',
'pw_2x1': 'Organize a "2-for-1" cremation deal if they bring their own firewood.',
'pw_ganges': 'Sell a stranger\'s ashes as "Holy Sand from the Ganges".',
'pw_youth': 'Apply for a "Youth Employment" grant for Ivan\'s apprentices.',
'pw_fridge': 'Convince a family the fridge noises are "messages from beyond".',
'pw_organic': 'Claim the embalming fluid is "100% organic and gluten-free".',
'pw_selfie': 'Charge a "Selfie Tax" for teenagers taking photos with the casket.',
'pw_air': 'Sell "Premium Scented Air" (an open window) for $50.',
'pw_viking': 'Offer a "Viking Funeral" in the office sink for a hamster.',
'pw_insurance': 'Try to claim "accidental death" for a client who died of old age.',
// Embalming
'emb.title': 'EMBALMING ROOM', 'emb.subtitle': 'Preserve dignity.',
'emb.no_body': 'No body to prepare', 'emb.preparing': 'Preparing: {0}',
'emb.tasks': 'TASKS', 'emb.clean': 'Clean', 'emb.treat': 'Treat', 'emb.dress': 'Dress', 'emb.prepare': 'Prepare',
'emb.supplies': 'SUPPLIES', 'emb.quality': 'QUALITY',
'emb.buy': '🛒 BUY SUPPLIES', 'emb.roll': 'ROLL D20 — EMBALM!',
'emb.no_chemicals': '⚠️ Not enough chemicals!', 'emb.no_outfits': '⚠️ No outfits left!',
'emb.finish': '🎲 FINISH & ROLL {0}',
'emb.q_excellent': '✨ {0} looks better dead than most people alive. Masterwork!',
'emb.q_catastrophic_list': [
    "The jaw drops as if screaming for BRAAAINS!",
    "One eye is clearly a poorly painted ping-pong ball.",
    "It looks like you used glitter instead of talcum powder.",
    "One arm is stuck in a wave. Such a polite customer.",
    "The stitched smile looks like a budget comic book villain.",
    "You used so much glue the eyelids look like closed shutters."
],
'emb.q_bad_list': [
    "The collar is so tight that button is now a lethal projectile.",
    "The pink dye makes them look like they spent too much time in a deep fryer.",
    "You put the shoes on the wrong feet, but hey, they aren't going for a jog.",
    "The skin has a suspicious shine, as if you've waxed them like a car.",
    "They smell more like a car air freshener than fresh flowers.",
    "The wig is so crooked it looks like they just came from a rock concert."
],
'emb.q_mediocre_list': [
    "They have the expression of someone who just remembered they left the stove on.",
    "You covered the dark circles with so much makeup they look like a professional mime.",
    "The hairstyle is... creative. Let's call it a 'post-life trend'.",
    "Not scary, but not exactly inviting for a hug either.",
    "It's acceptable, as long as the family doesn't use a magnifying glass... or eyes.",
    "Neither good nor bad, just... present. Very present."
],
'emb.q_good_list': [
    "They look so good you almost expect them to ask for the bill.",
    "You've captured their 'essence'. Whatever that smell lingering in the air is.",
    "They look better than in their ID photo. Not hard, but still impressive.",
    "The skin tone is perfect—not too pale, not too neon pink.",
    "Ready for their final big party. At least they're well-dressed.",
    "Dignified work. The family can sleep soundly... and so can you."
],
'emb.q_excellent_list': [
    "There's so much hairspray you could use their head to break diamonds.",
    "It's a masterpiece. You should sign it somewhere discreet.",
    "So flawless it's a shame to bury them. Maybe for a museum?",
    "You've made it look like they're just taking an exceptionally long nap.",
    "Even Ivan stopped complaining when he saw this. Now that's a miracle.",
    "If it wasn't for the whole 'not breathing' thing, I'd ask them out."
],
'emb.needs_embalming': '🧪 {0} needs embalming!',
'emb.still_needs': '🧪 {0} still needs embalming!',
'emb.penalty': '({0} Penalty)', 'emb.no_penalty': '(No Penalty)',
// Embalming tutorial
'emb.tutorial_title': '🧪 FIRST TIME IN THE EMBALMING ROOM',
'emb.tutorial_text': 'Remember to keep your supplies stocked — they take 1 hour to arrive after ordering. Running out mid-procedure is... awkward.',
'emb.tutorial_ok': 'Got it, stock up early',
// Cafeteria
'cafe.title': 'CAFETERIA', 'cafe.subtitle': 'For the living, too.',
'cafe.menu': '☕ DEADLY GOOD MENU', 'cafe.orders': '📝 ORDERS',
'cafe.pour': 'POUR', 'cafe.steep': 'STEEP!', 'cafe.preparing': 'PREPARING {0}',
'cafe.coffee': 'COFFEE', 'cafe.tea': 'TEA', 'cafe.sandwich': 'SANDWICH', 'cafe.soul_cake': 'SOUL CAKE',
'cafe.tut_pour': 'Hold to fill and release in the zone!',
'cafe.tut_steep': 'Click when the bag goes down 3 times!',
'cafe.tut_assemble': 'Follow the recipe order!',
'cafe.tut_decorate': 'Memorize the pattern and repeat it!',
'cafe.watch': 'WATCH...', 'cafe.your_turn': 'YOUR TURN!',
'cafe.fb_spilled': 'SPILLED! A mess...', 'cafe.fb_perfect': 'PERFECT POUR!',
'cafe.fb_good': 'GOOD ENOUGH.', 'cafe.fb_little': 'TOO LITTLE...',
'cafe.fb_missed': 'MISSED!', 'cafe.fb_steeps': 'STEEPS: {0}/3', 'cafe.fb_perfect_brew': 'PERFECT BREW!',
'cafe.fb_delicious': 'DELICIOUS!', 'cafe.fb_wrong': 'WRONG ORDER!',
'cafe.fb_beautiful': 'BEAUTIFUL!', 'cafe.fb_ouija': 'OUIJA SAYS NO!',
'cafe.satisfaction': '😊 SATISFACTION', 'cafe.no_orders': 'No active orders right now.',
'cafe.no_orders_yet': 'No orders yet', 'cafe.served': 'Served',
'cafe.alcohol_title': '🍺 ALCOHOL REQUEST', 'cafe.alcohol_request': 'Alcohol request',
// Crematorium
'crema.title': 'CREMATORIUM', 'crema.subtitle': 'Reduction to essentials.',
'crema.temp': '🌡️ TEMPERATURE', 'crema.fuel': '⛽ FUEL', 'crema.efficiency': '📊 EFFICIENCY',
'crema.schedule': "TODAY'S SCHEDULE", 'crema.no_scheduled': 'No cremations scheduled',
'crema.add_fuel': '⛽ ADD FUEL ($50)', 'crema.ignite': '🔥 IGNITE',
'crema.no_money_fuel': 'Not enough money for fuel!', 'crema.fuel_full': 'Fuel tank is full!',
'crema.already_burning': 'Already burning!', 'crema.add_fuel_first': 'Add fuel first!',
'crema.ignited': '🔥 Crematorium ignited! Temperature rising...',
'crema.fuel_depleted': '🔥 Crematorium fuel depleted!',
'crema.cremating': '🔥 {0} is being cremated... It will take 1 hour.',
'crema.done_desc': 'Cremation of {0} has finished.',
'crema.waiting': '🔥 The family of {0} is waiting for cremation.',
'crema.btn_cremate': 'CREMATE', 'crema.need_800': '⏳ Need 800°C',
'crema.incinerating': '🔥 INCINERATING...',
'crema.eff_perfect': 'Perfect!', 'crema.eff_heating': 'Heating...', 'crema.eff_warming': 'Warming up',
'crema.perfect_msg': '✨ Perfect cremation! {0}\'s ashes are clean and pure.',
'crema.decent_msg': '👍 Decent cremation. Some fragments remain, but acceptable.',
'crema.bad_msg': '😬 Bad cremation. The results are... suboptimal. The family is not happy.',
// Crematorium tutorial
'crema.tutorial_title': '🔥 FIRST TIME IN THE CREMATORIUM',
'crema.tutorial_text': 'The furnace takes time to heat up. Once cremation begins, it must stay lit for 1 hour to produce good, clean ashes. If the temperature drops below 700°C during the process... let\'s just say the family won\'t be pleased.',
'crema.tutorial_ok': 'Understood, keep the fire burning',
// Viewing
'view.title': 'VIEWING ROOM', 'view.subtitle': 'A final goodbye.',
'view.mood': '👨‍👩‍👧 FAMILY MOOD', 'view.requests': '📋 REQUESTS',
'view.no_active': 'No active viewing',
'view.show_body': 'SHOW BODY', 'view.water': 'BRING WATER', 'view.temp': 'ADJUST TEMP', 'view.firstaid': 'FIRST AID',
'view.water_served': '💧 Water served. Small gestures matter.',
'view.temp_adjusted': '❄️ Temperature adjusted. Much better.',
'view.no_ac': '⚠️ No A/C system! Buy it in Upgrades.',
'view.firstaid_done': '🩹 First aid administered! Crisis averted!',
'view.no_firstaid': '⚠️ No First Aid Kit! Someone is still on the floor!',
'view.all_fulfilled': 'All requests fulfilled.',
'view.already_seen': 'They have already seen the body.',
'view.no_water_needed': 'They are not thirsty right now.',
'view.no_temp_needed': 'They are comfortable with the temperature.',
'view.no_firstaid_needed': 'No one needs first aid.',
'view.sorry': 'I am so sorry...',
'view.glad_goodbye': 'Goodbye, rest in peace.',
'view.body_title': '👁️ VIEWING — {0}',
// Viewing tutorial
'view.tutorial_title': '👁️ FIRST TIME IN THE VIEWING ROOM',
'view.tutorial_text': 'Families can ask for anything. Have everything ready — water, temperature control, first aid — to earn reputation. Happy families mean better ratings.',
'view.tutorial_ok': 'Got it, be prepared',
// Chapel
'chapel.title': 'THE CHAPEL', 'chapel.subtitle': 'Faith. Ritual. Comfort.',
'chapel.ivan': 'Iván — The Orator', 'chapel.service': '🕯️ SERVICE TYPE',
'chapel.no_service': 'No service scheduled', 'chapel.select_sermon': '📜 SELECT SERMON',
'chapel.comfort': 'COMFORT', 'chapel.begin': 'BEGIN CEREMONY',
'chapel.correct': 'Beautiful ceremony, Ivan.', 'chapel.wrong': 'Oh no...',
'chapel.ivan_speaks': '🎤 IVAN SPEAKS',
'chapel.ceremony_for': 'Ceremony for:', 'chapel.religion': 'Religion:',
'chapel.waiting_toast': '🎤 {0} is waiting for the ceremony in the Chapel!',
'chapel.wrong_1': 'Ivan, please! That is not a psalm, it is a grocery list!',
'chapel.wrong_2': 'What are you saying! {name} was of a different faith! How disrespectful!',
'chapel.wrong_3': 'The family looks on in horror as Ivan accidentally tries to improvise a satanic rite.',
'chapel.wrong_4': 'Pasta? Did he say spaghetti? This is a funeral, not an Italian dinner!',
'chapel.wrong_5': 'That is not the holy book! It is a tractor repair guide!',
'chapel.wrong_6': 'Stop! {name} would roll in their grave if they heard these blasphemies!',
'chapel.wrong_7': 'The speaker starts reciting Heavy Metal lyrics. Grandma just fainted.',
'chapel.wrong_8': 'That is a Viking ritual and we are Buddhist! Ivan, focus!',
'chapel.wrong_9': 'Ivan mistakes the deceased for a Jedi. The force is NOT with us today.',
'chapel.wrong_10': 'How embarrassing! He called the deceased by his dog\'s name!',
'chapel.retry': 'RETRY CEREMONY',
// Chapel tutorial
'chapel.tutorial_title': '⛪ FIRST TIME IN THE CHAPEL',
'chapel.tutorial_text': 'Make sure to check the family\'s religious belief in the Families menu before opening your mouth. Choosing the wrong sermon can be... catastrophic.',
'chapel.tutorial_ok': 'Got it, I\'ll check first',
// Violin music
'chapel.violin_offer_title': '🎻 MUSICAL ACCOMPANIMENT',
'chapel.violin_offer_text_1': "You're in luck, it's Aida the violinist's turn. She plays so well even the dead try to keep the beat. (Cost: $40)",
'chapel.violin_offer_text_2': "You're in luck, it's Aida the violinist's turn. Her music is so sad she'll charge you extra for the tears. (Cost: $40)",
'chapel.violin_offer_text_3': "You're in luck, it's Aida the violinist's turn. Watch out, or that violin bow might end up in an eye. (Cost: $40)",
'chapel.violin_offer_text_4': "You're in luck, it's Aida the violinist's turn. She claims the violin is made from recycled coffin wood. (Cost: $40)",
'chapel.violin_offer_text_5': "You're in luck, it's Aida the violinist's turn. Her high notes could wake up an entire mausoleum. (Cost: $40)",
'chapel.violin_offer_yes': 'Offer violin music ($40)',
'chapel.violin_offer_no': 'Skip the music',
'chapel.violin_accept_title': '🎻 AIDA PERFORMS',
'chapel.violin_decline_title': '🎻 MUSIC DECLINED',
'chapel.violin_income': 'Violin performance by Aida',
'chapel.violin_bravo': 'Bravo, Aida!',
'chapel.violin_ok': 'Fair enough.',
'chapel.aida_quote_1': 'Aida, the prodigious, the sublime, the one-and-only violinist who once made a statue cry, plays a melody so beautiful that even the deceased seems to smile. Several family members are weeping. One is recording it on their phone.',
'chapel.aida_quote_2': 'Aida, virtuoso extraordinaire and self-proclaimed "angel of strings", begins a delicate adagio. A fly in the chapel stops mid-air to listen. Truly, she is a gift to the mortal realm.',
'chapel.aida_quote_3': 'Aida, whose talent has been described as "alarming" by at least three orchestras, performs a hauntingly beautiful piece. The family is deeply moved. Someone whispers: "Can she play at MY funeral too?"',
'chapel.aida_quote_4': 'The magnificent Aida, who claims to have studied under a ghost in Vienna, fills the chapel with notes so pure they could resurrect the dead. They don\'t, of course. That would be a liability issue.',
'chapel.aida_quote_5': 'Aida, legend of the strings, rumored to tune her violin with tears of joy, plays a piece that makes everyone forget they\'re in a funeral home. For about 4 minutes, anyway.',
'chapel.violin_reject_1': 'The family politely declines. "Thank you, but uncle Jorge always said violins sounded like angry cats." Fair enough.',
'chapel.violin_reject_2': 'The family says no. "We appreciate it, but the deceased specifically requested silence. And a kazoo, but we\'re ignoring that part."',
'chapel.violin_reject_3': '"No thank you. Last time we had live music at a funeral, grandma started dancing. She wasn\'t the deceased."',
// Office
'office.title': 'UPGRADES', 'office.subtitle': 'Invest in death.',
// Families
'fam.title': 'FAMILIES LOG', 'fam.subtitle': 'Those we\'ve served.',
'fam.no_families': 'No families yet. Death takes a day off?',
'fam.active': '● ACTIVE', 'fam.waiting': '● WAITING FOR HEARSE', 'fam.completed': '✓ COMPLETED',
'fam.rating': 'Rating', 'fam.satisfaction': 'Satisfaction', 'fam.transport': 'Transport',
'fam.services': 'Services', 'fam.earned': 'Earned', 'fam.rep': 'Reputation',
'fam.cremated_onsite': '🔥 Cremated on-site', 'fam.hearse_transfer': '🚗 Transferred by hearse',
'fam.embalmed': '✓ Embalmed', 'fam.not_embalmed': '✗ Not embalmed',
'fam.viewing_done': '✓ Viewing done', 'fam.chapel_service': '✓ Chapel service',
'fam.cremation_done': '✓ Cremated', 'fam.basic_only': 'Basic only',
'fam.departed': '☠ {0} — DEPARTED',
'fam.service_complete': 'All services for {0} are complete. Go to Reception and call a hearse for transfer.',
'fam.transfer_desc': '🚐 Transfer {0}',
// Game Over
'go.title': 'GAME OVER', 'go.try_again': 'TRY AGAIN',
'go.bankrupt_title': 'BANKRUPT', 'go.bankrupt_reason': 'You ran out of money. Even death costs money, apparently.',
'go.disgraced_title': 'DISGRACED', 'go.disgraced_reason': 'Your reputation hit rock bottom. Nobody trusts you with their dead.',
'go.money_warning': '⚠️ WARNING: Money running low! (${0})',
'go.rep_warning': '⚠️ WARNING: Reputation dangerously low!',
'go.days': 'Days survived:', 'go.served': 'Families served:', 'go.earnings': 'Total earnings:',
'go.best_roll': 'Best dice roll:', 'go.level': 'Level reached:',
// Overlays
'ov.service_complete': '☠ SERVICE COMPLETE',
'ov.level_up': 'NEW RANK ACHIEVED!',
'ov.reward': 'REWARD:',
'ov.summary_deceased': 'Deceased',
'ov.summary_rating': 'Rating',
'ov.summary_satisfaction': 'Satisfaction',
'ov.summary_transport': 'Transport',
'ov.summary_services': 'Services',
'ov.summary_earned': 'Earned',
'ov.summary_reputation': 'Reputation',
'ov.summary_departed': 'DEPARTED',
'ov.saved': '💾 PROGRESS SAVED!',
'ov.summary_basic': 'Basic only',
'ov.summary_ordered': 'Ordered',
'ov.summary_cremated': 'Cremated',
'ov.summary_chapel': 'Chapel',
'ov.summary_flowers': 'Flowers',
'ov.summary_viewing': 'Viewing',
'ov.summary_embalmed': 'Embalmed',
'ov.summary_not_embalmed': 'Not embalmed',
'ov.summary_cremated_onsite': '🔥 Cremated on-site',
'ov.summary_hearse_transfer': '🚗 Transferred by hearse',
'ov.status_waiting': '● WAITING FOR HEARSE',
'ov.status_active': '● ACTIVE',
'ov.status_completed': '✓ COMPLETED',
'ov.no_families': 'No families yet. Death takes a day off?',
'ov.dismiss': 'DISMISS',
'ov.shop_title': '🛒 SUPPLY MARKET',
'ov.shop_subtitle': 'Prices fluctuate daily. Buy wisely.',
'ov.shop_cancel': 'CANCEL',
'ov.shop_buy': 'BUY',
'ov.shop_select': 'Select at least one item!', 'ov.shop_no_money': 'Not enough money! Need ${0}.',
'ov.shop_delivered': '📦 Supplies delivered!',
'shop.mood_clearance': '📉 Supplier clearance! Prices low.',
'shop.mood_normal': '📦 Normal market conditions.',
'shop.mood_high': '📈 High demand. Prices elevated.',
'shop.mood_shortage': '💀 Critical shortage. Prices through the roof!',
'shop.in_stock': 'In stock: {0} {1}',
'shop.ea': 'ea',
'shop.select_item': 'Select at least one item!',
'shop.no_money': 'Not enough money! Need ${0}.',
'shop.delivery_desc': '📦 Supplies Delivery',
'shop.delivered': '📦 Supplies ordered. Delivery in 1h.',
'ov.credits_title': '♱ CREDITS', 'ov.credits_game': 'A game about death, paperwork, and terrible coffee.',
'ov.credits_design': 'Game Design & Concept: K. Arlón', 'ov.credits_ivan': 'Orator: Iván (he insisted)',
'ov.credits_quote': '"Life is temporary. Paperwork is eternal."', 'ov.back': 'BACK',
'ov.roll': 'ROLL!',
// Engine
'eng.new_pw': 'Paperwork scheduled at {0}',
'eng.end_title': '🛌 END OF DAY', 'eng.end_text': 'It seems there are no more tasks for today. Do you want to go to sleep?',
'eng.end_yes': 'YES, GO TO SLEEP', 'eng.end_no': 'NOT YET',
'eng.end_stay': 'You decided to stay up a bit longer.',
'eng.day_ended': '🌙 Day {0} ended. A new day dawns at Eternal Rest.',
'eng.daily_expenses': 'Daily expenses (Day {0})',
'eng.level_up': '🎉 LEVEL UP! You are now Level {0}!',
'eng.level_bonus': 'HQ Level Up Bonus',
'eng.need_level': 'Need Level {0}!', 'eng.not_enough': 'Not enough money!',
'eng.max_training': 'Max training reached!',
'eng.arrival_desc': 'New family, appointment at {0}',
'eng.pw_desk': 'New paperwork on your desk!',
'eng.cremation_family': 'A family is here for a cremation service.',
'eng.supply_purchase': 'Supply purchase',
'eng.paperwork_success': 'Paperwork success',
'eng.paperwork_failed': 'Paperwork failed',
'eng.dialogue_choice': 'Dialogue choice',
'eng.job_call': 'Job Interview Call',
'eng.ordered_flowers': 'Ordered Flowers',
'eng.ordered_hearse': 'Ordered Hearse',
'eng.ok': 'OK',
// Dialogue
'dlg.new_arrival': 'NEW ARRIVAL', 'dlg.family_registered': '📋 FAMILY REGISTERED',
'dlg.deceased': 'Deceased:', 'dlg.age': 'Age:', 'dlg.sex': 'Sex:',
'dlg.religion': 'Religion:', 'dlg.cause': 'Cause:', 'dlg.service': 'Service:',
'dlg.cremation': '🔥 Cremation', 'dlg.burial': '⚰️ Burial',
'dlg.viewing_req': '👁️ Viewing requested', 'dlg.chapel_req': '⛪ Chapel service requested',
'dlg.understood': 'UNDERSTOOD, PROCEED',
// Dice
'dice.modifier': 'Modifier: {0}',
'dice.crit_fail': '💀 CRITICAL FAIL!', 'dice.catastrophic': '🔥 Catastrophic!',
'dice.bad': '😬 Bad...', 'dice.mediocre': '😐 Mediocre',
'dice.good': '👍 Good!', 'dice.great': '✨ Great!',
'dice.crit_success': '💀✨ CRITICAL SUCCESS!',
'dice.result': 'Rolled {0} = {1} — {2}',
// Shop labels
'shop.formaldehyde': 'Formaldehyde', 'shop.humectant': 'Humectant',
'shop.dye': 'Cosmetic Dye', 'shop.outfit': 'Burial Outfit',
'shop.in_stock': 'In stock: {0} {1}',
'shop.market_cheap': '📉 Supplier clearance! Prices low.',
'shop.market_normal': '📦 Normal market conditions.',
'shop.market_high': '📈 High demand. Prices elevated.',
'shop.market_critical': '💀 Critical shortage. Prices through the roof!',
// Language
'shop.vials': 'vials', 'shop.jars': 'jars', 'shop.tubes': 'tubes', 'shop.sets': 'sets',
'rec.pw_dc': 'Difficulty (DC): {0}',
'rec.personal_enroute': '🚗 (Personal car en route) - {0}',
'rec.personal_pickup': 'Personal car transfer for {0} at {1}',
'off.trained': 'Trained: {0}/{1}',
'crema.done_desc': 'Cremation of {0} finished.',
'crema.need_800': 'Wait for 800°C',
'crema.incinerating': '🔥 Incinerating...',
'crema.btn_cremate': '🔥 CREMATE',
'rec.niece_desc': '🚗 Your niece can take one body for free.',
'crema.ready_desc': '{0} is ready for cremation.',
'rec.arrival_pickup': 'Request hearse transfer for {0}',
'cafe.inspector_title': '🚨 HEALTH INSPECTOR',
'cafe.inspector_msg': 'Stop right there! I am a secret health inspector. You have been caught serving illegal alcohol multiple times today. This establishment is closed until further notice!',
'cafe.inspector_ok': 'UNDERSTOOD',
'dlg.male': 'Male', 'dlg.female': 'Female',
'dlg.needs_embalming': '🧪 {0} needs embalming!',
'dlg.family_title': "Family of {0}",
'eng.alert_18_title': 'ALERT!',
'eng.alert_18_msg': 'Quick, finish all your tasks, the funeral home closes in 2 hours!',
// Moods
'mood.crying.name': 'Devastated', 'mood.crying.desc': 'They can barely speak through the tears.',
'mood.celebrating.name': 'Celebrating', 'mood.celebrating.desc': 'They brought confetti. To a funeral home.',
'mood.zen.name': 'Zen', 'mood.zen.desc': 'Eerily calm. Like, unsettlingly calm.',
'mood.drunk.name': 'Intoxicated', 'mood.drunk.desc': 'They smell like a distillery had a baby with a pharmacy.',
'mood.arguing.name': 'Fighting', 'mood.arguing.desc': 'The inheritance discussion started in the parking lot.',
'mood.flirty.name': 'Flirtatious', 'mood.flirty.desc': 'Someone is definitely hitting on you. At their relative\'s funeral intake.',
'mood.paranoid.name': 'Suspicious', 'mood.paranoid.desc': 'They keep asking if you\'re SURE their relative is dead.',
'mood.cheerful.name': 'Relieved', 'mood.cheerful.desc': '"To be honest, Uncle was kind of a jerk."',
'mood.vampire.name': 'Gothic', 'mood.vampire.desc': 'They seem to be waiting for the deceased to wake up.',
'mood.alien.name': 'Extraterrestrial', 'mood.alien.desc': 'They suspect the deceased was a cosmic observer.',
'mood.influencer.name': 'Trending', 'mood.influencer.desc': 'Everything is a photo opportunity. Even this.',
'mood.gamer.name': 'Gamer', 'mood.gamer.desc': 'They keep looking for the \'respawn\' button.',
'mood.clone.name': 'Suspicious', 'mood.clone.desc': 'They are convinced this body is a government clone.',
'mood.tax.name': 'Scheming', 'mood.tax.desc': 'They need one last \'signature\' from the deceased.',
'mood.steampunk.name': 'Mechanized', 'mood.steampunk.desc': 'They want to add brass gears to the coffin.',
'mood.reality.name': 'Dramatic', 'mood.reality.desc': 'They are treating this like a season finale.',
'mood.coupon.name': 'Frugal', 'mood.coupon.desc': 'They brought a stack of expired coupons.',
'mood.traveler.name': 'Temporal', 'mood.traveler.desc': 'They claim the deceased will revive in a week.',
// New Dialogues
'dlg.vampire.text': '"No stakes, please. {name} is just waiting for the full moon to wake up."',
'dlg.vampire.c1': '"I understand, we will use red silk and no garlic."',
'dlg.vampire.c2': '"As long as you pay the night surcharge, they can wait for Dracula."',
'dlg.vampire.c3': '"This is a funeral home, not the set of Twilight."',
'dlg.alien.text': '"Don\'t open the chest! {name}\'s microchip might send a war signal to the Orion nebula."',
'dlg.alien.c1': '"Don\'t worry, we work with electromagnetic shielding."',
'dlg.alien.c2': '"Does it come with propulsion technology? Scrap yards pay well..."',
'dlg.alien.c3': '"I\'ll call the Men in Black. Ivan has a similar suit."',
'dlg.influencer.text': '"Hey followers! We\'re here with {name}\'s body. Do you think this \'Glamorous Death\' filter looks good?"',
'dlg.influencer.c1': '"Tag us in the post. Let people notice the professional\'s work!"',
'dlg.influencer.c2': '"If you want the \'Trending Topic\' pack, it\'s 200 extra coins."',
'dlg.influencer.c3': '"Put the phone away or the next livestream will be from the incinerator."',
'dlg.gamer.text': '"Damn it, {name} is out of lives. Real life lag is horrible. Do you have any cheat codes?"',
'dlg.gamer.c1': '"I\'m sorry, {name}\'s server has permanently closed. F."',
'dlg.gamer.c2': '"We can do a symbolic \'respawn\' in the chapel."',
'dlg.gamer.c3': '"Stop pressing buttons! There\'s no pause button here."',
'dlg.clone.text': '"Look at the right earlobe. This isn\'t {name}! It\'s a CIA plant!"',
'dlg.clone.c1': '"We will analyze the DNA discreetly. Trust us."',
'dlg.clone.c2': '"True, the original is on an island with Elvis. This is a decoy."',
'dlg.clone.c3': '"Ma\'am, the earlobe changes with death. It\'s basic science."',
'dlg.tax.text': '"Quick, can you move {name}\'s arm? I need them to sign this will... I mean, this fishing permit."',
'dlg.tax.c1': '"Rigor mortis is very strict with legal signatures."',
'dlg.tax.c2': '"For a price, I can make {name} \'sign\' even a mortgage contract."',
'dlg.tax.c3': '"I\'ll call the police. Or the tax office. Whichever is scarier."',
'dlg.steampunk.text': '"We want {name}\'s coffin to have exhaust valves and run on a steam boiler."',
'dlg.steampunk.c1': '"Splendid. We\'ll add brass gears for a small extra."',
'dlg.steampunk.c2': '"The post-apocalyptic Victorian aesthetic will look great."',
'dlg.steampunk.c3': '"This is going to explode. Literally."',
'dlg.reality.text': '"NOOOOO! Why didn\'t you take me instead, {name}?! *looks at camera waiting for applause*"',
'dlg.reality.c1': '"What a performance! I mean... what profound pain!"',
'dlg.reality.c2': '"Cut. Let\'s repeat the take with more tears."',
'dlg.reality.c3': '"Can I get your autograph? I\'ve seen all your previous funerals."',
'dlg.coupon.text': '"I found this \'Pay 1 Dead, Get 2\' coupon in a 1994 magazine. Does it work?"',
'dlg.coupon.c1': '"It\'s vintage, I love it. I\'ll give you a 10% discount."',
'dlg.coupon.c2': '"Sir, this is a funeral home, not a supermarket."',
'dlg.coupon.c3': '"Only if you bring the second body yourself right now."',
'dlg.traveler.text': '"I\'ve come back from 2045 to tell you that {name} revives next Tuesday. Don\'t seal the coffin too tight."',
'dlg.traveler.c1': '"I\'ll put an emergency exit just in case."',
'dlg.traveler.c2': '"Tell me the lottery number and I\'ll give you the funeral for free."',
'dlg.traveler.c3': '"And in the future, is the machine coffee still this bad?"',
'rec.select_transport': 'Select family for transport:',
'rec.hearse_ordered_for': 'Hearse ordered for the family of {0}.',
'rec.no_family_transport': 'There are no families waiting for transport right now.',
'rec.nevermind': 'Nevermind',
'crema.disposal_warning': '⚠️ Some bodies were discarded because they were not cremated on time.',
'dlg.bad_luck': 'UNEXPECTED MISHAP!',
'bad.roof_rats': '🏚️ The chapel roof has collapsed under the weight of rat nests made of human hair.',
'bad.broken_lighter': '🔥 The oven lighter is broken. You had to use a kitchen blowtorch and burned the curtains.',
'bad.coffee_explosion': '☕ The coffee machine exploded, splashing boiling "coffee" on a mourning family.',
'bad.termite_coffin': '🐜 Mutant termites have devoured a display coffin in record time.',
'bad.wrong_air': '🌲 The ventilation system is pumping out "Intense Pine" air freshener at toxic levels.',
'bad.ghost_complaint': '👻 A spirit has manifested just to complain that the background music is "too modern".',
'bad.tax_error': '⚖️ An administrative error says the mortuary is actually a daycare. Immediate fine.',
'bad.slip_fall': '🚑 An inspector slipped on a puddle of formaldehyde. Lawsuit on the way.',
'bad.stolen_urn': '🐦 A crow has flown off with an urn, thinking it was a shiny nest.',
'bad.cursed_phone': '📞 The reception phone won\'t stop ringing with EVP recordings of people ordering pizza.',
'spl.click_to_enter': '[ CLICK TO ENTER THE CRYPT ]',
});
