/* ===== English Strings ===== */
I18n.register('en', {
// Title
'splash.loading': 'Loading worms...',
'title.tagline': 'A Management RPG About Life in a Funeral House',
'title.quote': '"You don\'t save lives. You help end them... professionally."',
'title.new_game': 'NEW GAME', 'title.continue': 'LOAD GAME', 'title.resume': 'RESUME', 'title.credits': 'CREDITS',
'title.save': 'SAVE', 'title.exit': 'EXIT',
'title.exit_confirm': 'Are you sure you want to exit? Unsaved progress will be lost.',
'title.footer': 'GAME DESIGN & CONCEPT BY K. ARLÓN<br>DARK HUMOR CONTENT — RATED BY DEATH INC.',
'credits.title': '♱ CREDITS',
'credits.desc': 'A game about death, paperwork, and terrible coffee.',
'credits.design': 'Game Design & Concept: K. Arlón',
'credits.orator': 'Orator: Iván (he insisted)',
'credits.quote': '"Life is temporary. Paperwork is eternal."',
'credits.back': 'BACK',
// Name
'name.title': 'WHO DARES RUN A FUNERAL HOME?', 'name.subtitle': 'Enter your name, future undertaker:',
'name.placeholder': 'Your name...', 'name.begin': 'BEGIN YOUR CAREER',
'name.error': 'Enter a name! Even the dead have names.',
'name.f1': '"Every great mortician started somewhere."', 'name.f2': '"Death is just the beginning... of your career."',
'name.f3': '"Your mother must be so proud."', 'name.f4': '"Hopefully you spell it right on the tombstones."',
'name.f5': '"The dead can\'t judge your name. The living will."',
// Welcome
'welcome.title': 'WELCOME TO THANATOPRACTOR',
'welcome.p1': 'Here we don\'t save lives, we just tie them up with a bow. Your job is simple: make up the dead so they look alive, burn them if the family doesn\'t want to see them anymore, and above all, don\'t get fond of necrophilia.',
'welcome.p2': 'By clicking below, you accept that formaldehyde is your new favorite cologne, that ghosts don\'t pay rent, and that we are not responsible for recurring nightmares or the sudden loss of your own soul.',
'welcome.accept': 'I ACCEPT THE TERMS',
// Hub
'hub.day': 'DAY', 'hub.reputation': 'REPUTATION', 'hub.schedule': "TODAY'S SCHEDULE",
'hub.no_appointments': 'No appointments yet...', 'hub.eternal_rest': 'ETERNAL REST',
'hub.funeral_house': 'FUNERAL HOUSE', 'hub.motto': '"We care to the end"',
'hub.welcome': '☠ Welcome, {0}. The dead await.',
'hub.locked': '🔒 Buy this room in the Upgrades menu!',
// Nav
'nav.reception': 'Reception', 'nav.embalming': 'Embalming', 'nav.cafeteria': 'Cafeteria',
'nav.crematorium': 'Cremator.', 'nav.viewing': 'Viewing', 'nav.chapel': 'Chapel',
'nav.upgrades': 'Upgrades', 'nav.families': 'Families',
// Reception
'rec.title': 'RECEPTION', 'rec.new_arrival': 'NEW ARRIVAL', 'rec.phone': 'PHONE CALL',
'rec.paperwork': 'PAPERWORK', 'rec.upgrades': 'UPGRADES',
'rec.appointments': "TODAY'S APPOINTMENTS", 'rec.no_appointments': 'No appointments today',
'rec.no_waiting': 'No families are waiting right now.',
'rec.phone_title': '📞 PHONE MENU', 'rec.phone_subtitle': 'Who would you like to call today?',
'rec.job_interview': 'Job Interview ($50)', 'rec.job_result': 'You called a candidate. They heard screaming in the background and hung up.',
'rec.order_hearse': 'Order Hearse ($150)', 'rec.hearse_ordered': 'Hearse ordered. The driver says he\'ll be there "eventually".',
'rec.hearse_multi': 'Hearse(s) ordered. Expect them in 1 hour.',
'rec.need_money_hearse': 'Need ${0} for {1} hearses!',
'rec.order_flowers': 'Order Flowers ($50)', 'rec.flowers_result': 'Fresh flowers delivered! The viewing room smells slightly less like formaldehyde.',
'rec.nevermind': 'Nevermind',
'rec.personal_hearse': '🚗 Use Personal Hearse (Free)',
'rec.niece_car': '🚗 Use Niece\'s Car (Free)',
'rec.car_cooldown': '🚗 Car on cooldown ({0}h)',
'rec.car_dispatched': '🚗 Car dispatched for {0}. It will be away for {1}h.',
'rec.niece_arrived': '🚗 Your niece arrived instantly! {0}\'s family has departed.',
'rec.car_busy': 'The car is currently out doing a transfer!',
'rec.no_family_transport': 'No families waiting for transport.',
'rec.no_paperwork': '📝 No paperwork right now. Enjoy the quiet.',
'rec.pw_title': '📝 PAPERWORK', 'rec.pw_roll': 'Roll D20',
'rec.pw_success': 'Success! You earned ${0}.', 'rec.pw_fail': 'Failure! You lost ${0}.',
'rec.pw_discarded': '📝 Paperwork discarded.', 'rec.pw_decline': '(Decline)',
'rec.hearse_picking': 'Hearse is picking up {0}\'s family.',
'rec.car_ordered': '📦 (Car ordered en route) - {0}',
// Embalming
'emb.title': 'EMBALMING ROOM', 'emb.subtitle': 'Preserve dignity.',
'emb.no_body': 'No body to prepare', 'emb.preparing': 'Preparing: {0}',
'emb.tasks': 'TASKS', 'emb.clean': 'Clean', 'emb.treat': 'Treat', 'emb.dress': 'Dress', 'emb.prepare': 'Prepare',
'emb.supplies': 'SUPPLIES', 'emb.quality': 'QUALITY',
'emb.buy': '🛒 BUY SUPPLIES', 'emb.roll': 'ROLL D20 — EMBALM!',
'emb.no_chemicals': '⚠️ Not enough chemicals!', 'emb.no_outfits': '⚠️ No outfits left!',
'emb.finish': '🎲 FINISH & ROLL {0}',
'emb.q_catastrophic': '💀 Oh no. {0} looks like a haunted wax figure. This will NOT end well.',
'emb.q_bad': '😬 {0} looks... off. Like they\'re judging you from beyond.',
'emb.q_mediocre': '😐 {0} looks acceptable. Not great, not terrible. Like a 3.6.',
'emb.q_good': '👍 {0} looks peaceful. Good job!',
'emb.q_excellent': '✨ {0} looks better dead than most people alive. Masterwork!',
'emb.needs_embalming': '🧪 {0} needs embalming!',
'emb.still_needs': '🧪 {0} still needs embalming!',
'emb.penalty': '({0} Penalty)', 'emb.no_penalty': '(No Penalty)',
// Embalming tutorial
'emb.tutorial_title': '🧪 FIRST TIME IN THE EMBALMING ROOM',
'emb.tutorial_text': 'Remember to keep your supplies stocked — they take 1 hour to arrive after ordering. Running out mid-procedure is... awkward.',
'emb.tutorial_ok': 'Got it, stock up early',
// Cafeteria
'cafe.title': 'CAFETERIA', 'cafe.subtitle': 'For the living, too.',
'cafe.menu': '☕ DEADLY GOOD MENU', 'cafe.orders': '📝 ORDERS',
'cafe.satisfaction': '😊 SATISFACTION', 'cafe.no_orders': 'No active orders right now.',
'cafe.no_orders_yet': 'No orders yet', 'cafe.served': 'Served',
'cafe.alcohol_title': '🍺 ALCOHOL REQUEST', 'cafe.alcohol_request': 'Alcohol request',
// Crematorium
'crema.title': 'CREMATORIUM', 'crema.subtitle': 'Reduction to essentials.',
'crema.temp': '🌡️ TEMPERATURE', 'crema.fuel': '⛽ FUEL', 'crema.efficiency': '📊 EFFICIENCY',
'crema.schedule': "TODAY'S SCHEDULE", 'crema.no_scheduled': 'No cremations scheduled',
'crema.add_fuel': '⛽ ADD FUEL ($50)', 'crema.ignite': '🔥 IGNITE',
'crema.no_money_fuel': 'Not enough money for fuel!', 'crema.fuel_full': 'Fuel tank is full!',
'crema.already_burning': 'Already burning!', 'crema.add_fuel_first': 'Add fuel first!',
'crema.ignited': '🔥 Crematorium ignited! Temperature rising...',
'crema.fuel_depleted': '🔥 Crematorium fuel depleted!',
'crema.cremating': '🔥 {0} is being cremated... It will take 1 hour.',
'crema.done_desc': 'Cremation of {0} has finished.',
'crema.waiting': '🔥 The family of {0} is waiting for cremation.',
'crema.btn_cremate': 'CREMATE', 'crema.need_800': '⏳ Need 800°C',
'crema.incinerating': '🔥 INCINERATING...',
'crema.eff_perfect': 'Perfect!', 'crema.eff_heating': 'Heating...', 'crema.eff_warming': 'Warming up',
'crema.perfect_msg': '✨ Perfect cremation! {0}\'s ashes are clean and pure.',
'crema.decent_msg': '👍 Decent cremation. Some fragments remain, but acceptable.',
'crema.bad_msg': '😬 Bad cremation. The results are... suboptimal. The family is not happy.',
// Crematorium tutorial
'crema.tutorial_title': '🔥 FIRST TIME IN THE CREMATORIUM',
'crema.tutorial_text': 'The furnace takes time to heat up. Once cremation begins, it must stay lit for 1 hour to produce good, clean ashes. If the temperature drops below 700°C during the process... let\'s just say the family won\'t be pleased.',
'crema.tutorial_ok': 'Understood, keep the fire burning',
// Viewing
'view.title': 'VIEWING ROOM', 'view.subtitle': 'A final goodbye.',
'view.mood': '👨‍👩‍👧 FAMILY MOOD', 'view.requests': '📋 REQUESTS',
'view.no_active': 'No active viewing',
'view.show_body': 'SHOW BODY', 'view.water': 'BRING WATER', 'view.temp': 'ADJUST TEMP', 'view.firstaid': 'FIRST AID',
'view.water_served': '💧 Water served. Small gestures matter.',
'view.temp_adjusted': '❄️ Temperature adjusted. Much better.',
'view.no_ac': '⚠️ No A/C system! Buy it in Upgrades.',
'view.firstaid_done': '🩹 First aid administered! Crisis averted!',
'view.no_firstaid': '⚠️ No First Aid Kit! Someone is still on the floor!',
'view.all_fulfilled': 'All requests fulfilled.',
'view.already_seen': 'They have already seen the body.',
'view.no_water_needed': 'They are not thirsty right now.',
'view.no_temp_needed': 'They are comfortable with the temperature.',
'view.no_firstaid_needed': 'No one needs first aid.',
'view.sorry': 'I am so sorry...',
'view.glad_goodbye': 'Goodbye, rest in peace.',
'view.body_title': '👁️ VIEWING — {0}',
// Viewing tutorial
'view.tutorial_title': '👁️ FIRST TIME IN THE VIEWING ROOM',
'view.tutorial_text': 'Families can ask for anything. Have everything ready — water, temperature control, first aid — to earn reputation. Happy families mean better ratings.',
'view.tutorial_ok': 'Got it, be prepared',
// Chapel
'chapel.title': 'THE CHAPEL', 'chapel.subtitle': 'Faith. Ritual. Comfort.',
'chapel.ivan': 'Iván — The Orator', 'chapel.service': '🕯️ SERVICE TYPE',
'chapel.no_service': 'No service scheduled', 'chapel.select_sermon': '📜 SELECT SERMON',
'chapel.comfort': 'COMFORT', 'chapel.begin': 'BEGIN CEREMONY',
'chapel.correct': 'Beautiful ceremony, Ivan.', 'chapel.wrong': 'Oh no...',
'chapel.ivan_speaks': '🎤 IVAN SPEAKS',
'chapel.ceremony_for': 'Ceremony for:', 'chapel.religion': 'Religion:',
'chapel.waiting_toast': '🎤 {0} is waiting for the ceremony in the Chapel!',
// Chapel tutorial
'chapel.tutorial_title': '⛪ FIRST TIME IN THE CHAPEL',
'chapel.tutorial_text': 'Make sure to check the family\'s religious belief in the Families menu before opening your mouth. Choosing the wrong sermon can be... catastrophic.',
'chapel.tutorial_ok': 'Got it, I\'ll check first',
// Violin music
'chapel.violin_offer_title': '🎻 MUSICAL ACCOMPANIMENT',
'chapel.violin_offer_text': 'The legendary, incomparable, devastatingly talented violinist Aida is available today. Would you like to offer the family a live violin performance during the ceremony? (Cost to the family: $40)',
'chapel.violin_offer_yes': 'Offer violin music ($40)',
'chapel.violin_offer_no': 'Skip the music',
'chapel.violin_accept_title': '🎻 AIDA PERFORMS',
'chapel.violin_decline_title': '🎻 MUSIC DECLINED',
'chapel.violin_income': 'Violin performance by Aida',
'chapel.violin_bravo': 'Bravo, Aida!',
'chapel.violin_ok': 'Fair enough.',
'chapel.aida_quote_1': 'Aida, the prodigious, the sublime, the one-and-only violinist who once made a statue cry, plays a melody so beautiful that even the deceased seems to smile. Several family members are weeping. One is recording it on their phone.',
'chapel.aida_quote_2': 'Aida, virtuoso extraordinaire and self-proclaimed "angel of strings", begins a delicate adagio. A fly in the chapel stops mid-air to listen. Truly, she is a gift to the mortal realm.',
'chapel.aida_quote_3': 'Aida, whose talent has been described as "alarming" by at least three orchestras, performs a hauntingly beautiful piece. The family is deeply moved. Someone whispers: "Can she play at MY funeral too?"',
'chapel.aida_quote_4': 'The magnificent Aida, who claims to have studied under a ghost in Vienna, fills the chapel with notes so pure they could resurrect the dead. They don\'t, of course. That would be a liability issue.',
'chapel.aida_quote_5': 'Aida, legend of the strings, rumored to tune her violin with tears of joy, plays a piece that makes everyone forget they\'re in a funeral home. For about 4 minutes, anyway.',
'chapel.violin_reject_1': 'The family politely declines. "Thank you, but uncle Jorge always said violins sounded like angry cats." Fair enough.',
'chapel.violin_reject_2': 'The family says no. "We appreciate it, but the deceased specifically requested silence. And a kazoo, but we\'re ignoring that part."',
'chapel.violin_reject_3': '"No thank you. Last time we had live music at a funeral, grandma started dancing. She wasn\'t the deceased."',
// Office
'office.title': 'UPGRADES', 'office.subtitle': 'Invest in death.',
// Families
'fam.title': 'FAMILIES LOG', 'fam.subtitle': 'Those we\'ve served.',
'fam.no_families': 'No families yet. Death takes a day off?',
'fam.active': '● ACTIVE', 'fam.waiting': '● WAITING FOR HEARSE', 'fam.completed': '✓ COMPLETED',
'fam.rating': 'Rating', 'fam.satisfaction': 'Satisfaction', 'fam.transport': 'Transport',
'fam.services': 'Services', 'fam.earned': 'Earned', 'fam.rep': 'Reputation',
'fam.cremated_onsite': '🔥 Cremated on-site', 'fam.hearse_transfer': '🚗 Transferred by hearse',
'fam.embalmed': '✓ Embalmed', 'fam.not_embalmed': '✗ Not embalmed',
'fam.viewing_done': '✓ Viewing done', 'fam.chapel_service': '✓ Chapel service',
'fam.cremation_done': '✓ Cremated', 'fam.basic_only': 'Basic only',
'fam.departed': '☠ {0} — DEPARTED',
'fam.service_complete': 'All services for {0} are complete. Go to Reception and call a hearse for transfer.',
'fam.transfer_desc': '🚐 Transfer {0}',
// Game Over
'go.title': 'GAME OVER', 'go.try_again': 'TRY AGAIN',
'go.bankrupt_title': 'BANKRUPT', 'go.bankrupt_reason': 'You ran out of money. Even death costs money, apparently.',
'go.disgraced_title': 'DISGRACED', 'go.disgraced_reason': 'Your reputation hit rock bottom. Nobody trusts you with their dead.',
'go.money_warning': '⚠️ WARNING: Money running low! (${0})',
'go.rep_warning': '⚠️ WARNING: Reputation dangerously low!',
'go.days': 'Days survived:', 'go.served': 'Families served:', 'go.earnings': 'Total earnings:',
'go.best_roll': 'Best dice roll:', 'go.level': 'Level reached:',
// Overlays
'ov.service_complete': '☠ SERVICE COMPLETE',
'ov.summary_deceased': 'Deceased',
'ov.summary_rating': 'Rating',
'ov.summary_satisfaction': 'Satisfaction',
'ov.summary_transport': 'Transport',
'ov.summary_services': 'Services',
'ov.summary_earned': 'Earned',
'ov.summary_reputation': 'Reputation',
'ov.summary_departed': 'DEPARTED',
'ov.saved': '💾 PROGRESS SAVED!',
'ov.summary_basic': 'Basic only',
'ov.summary_ordered': 'Ordered',
'ov.summary_cremated': 'Cremated',
'ov.summary_chapel': 'Chapel',
'ov.summary_flowers': 'Flowers',
'ov.summary_viewing': 'Viewing',
'ov.summary_embalmed': 'Embalmed',
'ov.summary_not_embalmed': 'Not embalmed',
'ov.summary_cremated_onsite': '🔥 Cremated on-site',
'ov.summary_hearse_transfer': '🚗 Transferred by hearse',
'ov.status_waiting': '● WAITING FOR HEARSE',
'ov.status_active': '● ACTIVE',
'ov.status_completed': '✓ COMPLETED',
'ov.no_families': 'No families yet. Death takes a day off?',
'ov.dismiss': 'DISMISS',
'ov.shop_title': '🛒 SUPPLY MARKET',
'ov.shop_subtitle': 'Prices fluctuate daily. Buy wisely.',
'ov.shop_cancel': 'CANCEL',
'ov.shop_buy': 'BUY',
'ov.shop_select': 'Select at least one item!', 'ov.shop_no_money': 'Not enough money! Need ${0}.',
'ov.shop_delivered': '📦 Supplies delivered!',
'shop.mood_clearance': '📉 Supplier clearance! Prices low.',
'shop.mood_normal': '📦 Normal market conditions.',
'shop.mood_high': '📈 High demand. Prices elevated.',
'shop.mood_shortage': '💀 Critical shortage. Prices through the roof!',
'shop.in_stock': 'In stock: {0} {1}',
'shop.ea': 'ea',
'shop.select_item': 'Select at least one item!',
'shop.no_money': 'Not enough money! Need ${0}.',
'shop.delivery_desc': '📦 Supplies Delivery',
'shop.delivered': '📦 Supplies ordered. Delivery in 1h.',
'ov.credits_title': '♱ CREDITS', 'ov.credits_game': 'A game about death, paperwork, and terrible coffee.',
'ov.credits_design': 'Game Design & Concept: K. Arlón', 'ov.credits_ivan': 'Orator: Iván (he insisted)',
'ov.credits_quote': '"Life is temporary. Paperwork is eternal."', 'ov.back': 'BACK',
'ov.roll': 'ROLL!',
// Engine
'eng.new_pw': '📝 New paperwork at {0}',
'eng.end_title': '🛌 END OF DAY', 'eng.end_text': 'It seems there are no more tasks for today. Do you want to go to sleep?',
'eng.end_yes': 'YES, GO TO SLEEP', 'eng.end_no': 'NOT YET',
'eng.end_stay': 'You decided to stay up a bit longer.',
'eng.day_ended': '🌙 Day {0} ended. A new day dawns at Eternal Rest.',
'eng.daily_expenses': 'Daily expenses (Day {0})',
'eng.level_up': '🎉 LEVEL UP! You are now Level {0}!',
'eng.level_bonus': 'HQ Level Up Bonus',
'eng.need_level': 'Need Level {0}!', 'eng.not_enough': 'Not enough money!',
'eng.max_training': 'Max training reached!',
'eng.arrival_desc': 'New family arriving at {0}',
'eng.pw_desk': 'New paperwork on your desk!',
'eng.cremation_family': 'A family is here for a cremation service.',
// Dialogue
'dlg.new_arrival': 'NEW ARRIVAL', 'dlg.family_registered': '📋 FAMILY REGISTERED',
'dlg.deceased': 'Deceased:', 'dlg.age': 'Age:', 'dlg.sex': 'Sex:',
'dlg.religion': 'Religion:', 'dlg.cause': 'Cause:', 'dlg.service': 'Service:',
'dlg.cremation': '🔥 Cremation', 'dlg.burial': '⚰️ Burial',
'dlg.viewing_req': '👁️ Viewing requested', 'dlg.chapel_req': '⛪ Chapel service requested',
'dlg.understood': 'UNDERSTOOD, PROCEED',
// Dice
'dice.modifier': 'Modifier: {0}',
'dice.crit_fail': '💀 CRITICAL FAIL!', 'dice.catastrophic': '🔥 Catastrophic!',
'dice.bad': '😬 Bad...', 'dice.mediocre': '😐 Mediocre',
'dice.good': '👍 Good!', 'dice.great': '✨ Great!',
'dice.crit_success': '💀✨ CRITICAL SUCCESS!',
'dice.result': 'Rolled {0} = {1} — {2}',
// Shop labels
'shop.formaldehyde': 'Formaldehyde', 'shop.humectant': 'Humectant',
'shop.dye': 'Cosmetic Dye', 'shop.outfit': 'Burial Outfit',
'shop.in_stock': 'In stock: {0} {1}',
'shop.market_cheap': '📉 Supplier clearance! Prices low.',
'shop.market_normal': '📦 Normal market conditions.',
'shop.market_high': '📈 High demand. Prices elevated.',
'shop.market_critical': '💀 Critical shortage. Prices through the roof!',
// Language
'shop.vials': 'vials', 'shop.jars': 'jars', 'shop.tubes': 'tubes', 'shop.sets': 'sets',
'rec.pw_dc': 'Difficulty (DC): {0}',
'rec.personal_enroute': '🚗 (Personal car en route) - {0}',
'rec.personal_pickup': 'Personal car is picking up {0}.',
'off.trained': 'Trained: {0}/{1}',
'crema.done_desc': 'Cremation of {0} finished.',
'crema.need_800': 'Wait for 800°C',
'crema.incinerating': '🔥 Incinerating...',
'crema.btn_cremate': '🔥 CREMATE',
'rec.niece_desc': '🚗 Your niece can take one body for free.',
'crema.ready_desc': '{0} is ready for cremation.',
'rec.arrival_pickup': 'Family of {0} arrived for pick-up.',
'cafe.inspector_title': '🚨 HEALTH INSPECTOR',
'cafe.inspector_msg': 'Stop right there! I am a secret health inspector. You have been caught serving illegal alcohol multiple times today. This establishment is closed until further notice!',
'cafe.inspector_ok': 'UNDERSTOOD',
'dlg.male': 'Male', 'dlg.female': 'Female',
'dlg.needs_embalming': '🧪 {0} needs embalming!',
'dlg.family_title': "Family of {0}",
});
