/* ===== Spanish Strings ===== */
I18n.register('es', {
// Title
'title.tagline': 'Un RPG de Gestión Sobre la Vida en un Tanatorio',
'title.quote': '"No salvas vidas. Les ayudas a terminar... profesionalmente."',
'title.new_game': 'NUEVA PARTIDA', 'title.continue': 'CONTINUAR', 'title.credits': 'CRÉDITOS',
'title.footer': 'DISEÑO Y CONCEPTO POR K. ARLÓN<br>HUMOR NEGRO — CLASIFICADO POR DEATH INC.',
// Name
'name.title': '¿QUIÉN SE ATREVE A DIRIGIR UNA FUNERARIA?',
'name.subtitle': 'Introduce tu nombre, futuro tanatopractor:',
'name.placeholder': 'Tu nombre...', 'name.begin': 'COMENZAR TU CARRERA',
'name.error': '¡Introduce un nombre! Hasta los muertos tienen nombre.',
'name.f1': '"Todo gran tanatopractor empezó en algún sitio."',
'name.f2': '"La muerte es solo el principio... de tu carrera."',
'name.f3': '"Tu madre debe estar muy orgullosa."',
'name.f4': '"Esperemos que lo escribas bien en las lápidas."',
'name.f5': '"Los muertos no pueden juzgar tu nombre. Los vivos sí."',
// Welcome
'welcome.title': 'BIENVENIDO A THANATOPRACTOR',
'welcome.p1': 'Aquí no salvamos vidas, solo las envolvemos con un lazo. Tu trabajo es simple: maquillar a los muertos para que parezcan vivos, quemarlos si la familia no quiere verlos más, y sobre todo, no preguntes por las manchas extrañas.',
'welcome.p2': 'Al hacer clic abajo, aceptas que el formaldehído es tu nueva colonia favorita, que los fantasmas no pagan alquiler, y que no somos responsables de pesadillas recurrentes ni de la pérdida repentina de tu propia alma.',
'welcome.accept': 'ACEPTO LOS TÉRMINOS',
// Hub
'hub.day': 'DÍA', 'hub.reputation': 'REPUTACIÓN', 'hub.schedule': 'AGENDA DE HOY',
'hub.no_appointments': 'Sin citas todavía...', 'hub.eternal_rest': 'DESCANSO ETERNO',
'hub.funeral_house': 'FUNERARIA', 'hub.motto': '"Cuidamos hasta el final"',
'hub.welcome': '☠ Bienvenido, {0}. Los muertos te esperan.',
'hub.locked': '🔒 ¡Compra esta sala en el menú de Mejoras!',
// Nav
'nav.reception': 'Recepción', 'nav.embalming': 'Embalsamar', 'nav.cafeteria': 'Cafetería',
'nav.crematorium': 'Cremat.', 'nav.viewing': 'Velatorio', 'nav.chapel': 'Capilla',
'nav.upgrades': 'Mejoras', 'nav.families': 'Familias',
// Reception
'rec.title': 'RECEPCIÓN', 'rec.new_arrival': 'NUEVA LLEGADA', 'rec.phone': 'LLAMAR',
'rec.paperwork': 'PAPELEO', 'rec.upgrades': 'MEJORAS',
'rec.appointments': 'CITAS DE HOY', 'rec.no_appointments': 'Sin citas hoy',
'rec.no_waiting': 'No hay familias esperando ahora mismo.',
'rec.phone_title': '📞 MENÚ TELEFÓNICO', 'rec.phone_subtitle': '¿A quién quieres llamar hoy?',
'rec.job_interview': 'Entrevista de trabajo ($50)',
'rec.job_result': 'Llamaste a un candidato. Oyó gritos de fondo y colgó.',
'rec.order_hearse': 'Pedir Coche Fúnebre ($150)',
'rec.hearse_ordered': 'Coche fúnebre pedido. El conductor dice que llegará "eventualmente".',
'rec.hearse_multi': 'Coche(s) fúnebre(s) pedido(s). Llegará(n) en 1 hora.',
'rec.need_money_hearse': '¡Necesitas ${0} para {1} coches fúnebres!',
'rec.order_flowers': 'Pedir Flores ($50)',
'rec.flowers_result': '¡Flores frescas entregadas! El velatorio huele un poco menos a formaldehído.',
'rec.nevermind': 'Nada, déjalo',
'rec.no_paperwork': '📝 Sin papeleo ahora mismo. Disfruta del silencio.',
'rec.pw_title': '📝 PAPELEO', 'rec.pw_roll': 'Tirar D20',
'rec.pw_success': '¡Éxito! Has ganado ${0}.', 'rec.pw_fail': '¡Fallo! Has perdido ${0}.',
'rec.pw_discarded': '📝 Papeleo descartado.', 'rec.pw_decline': '(Rechazar)',
'rec.hearse_picking': 'El coche fúnebre recoge a la familia de {0}.',
'rec.car_ordered': '📦 (Coche pedido en camino) - {0}',
// Embalming
'emb.title': 'SALA DE EMBALSAMAR', 'emb.subtitle': 'Preservar la dignidad.',
'emb.no_body': 'Sin cuerpo que preparar', 'emb.preparing': 'Preparando: {0}',
'emb.tasks': 'TAREAS', 'emb.clean': 'Limpiar', 'emb.treat': 'Tratar', 'emb.dress': 'Vestir', 'emb.prepare': 'Preparar',
'emb.supplies': 'SUMINISTROS', 'emb.quality': 'CALIDAD',
'emb.buy': '🛒 COMPRAR SUMINISTROS', 'emb.roll': '¡TIRAR D20 — EMBALSAMAR!',
'emb.no_chemicals': '⚠️ ¡No hay suficientes químicos!', 'emb.no_outfits': '⚠️ ¡No quedan trajes!',
'emb.finish': '🎲 FINALIZAR Y TIRAR {0}',
'emb.q_catastrophic': '💀 Oh no. {0} parece una figura de cera encantada. Esto NO va a acabar bien.',
'emb.q_bad': '😬 {0} se ve... raro. Como si te juzgara desde el más allá.',
'emb.q_mediocre': '😐 {0} se ve aceptable. Ni bien ni mal. Como un 3.6.',
'emb.q_good': '👍 {0} se ve en paz. ¡Buen trabajo!',
'emb.q_excellent': '✨ {0} se ve mejor muerto que la mayoría de la gente viva. ¡Obra maestra!',
'emb.needs_embalming': '🧪 ¡{0} necesita embalsamamiento!',
'emb.still_needs': '🧪 ¡{0} todavía necesita embalsamamiento!',
// Cafeteria
'cafe.title': 'CAFETERÍA', 'cafe.subtitle': 'También para los vivos.',
'cafe.menu': '☕ MENÚ MORTALMENTE BUENO', 'cafe.orders': '📝 PEDIDOS',
'cafe.satisfaction': '😊 SATISFACCIÓN', 'cafe.no_orders': 'Sin pedidos activos ahora mismo.',
'cafe.no_orders_yet': 'Sin pedidos aún', 'cafe.served': 'Servido',
'cafe.alcohol_title': '🍺 PETICIÓN DE ALCOHOL', 'cafe.alcohol_request': 'Petición de alcohol',
// Crematorium
'crema.title': 'CREMATORIO', 'crema.subtitle': 'Reducción a lo esencial.',
'crema.temp': '🌡️ TEMPERATURA', 'crema.fuel': '⛽ COMBUSTIBLE', 'crema.efficiency': '📊 EFICIENCIA',
'crema.schedule': 'AGENDA DE HOY', 'crema.no_scheduled': 'Sin cremaciones programadas',
'crema.add_fuel': '⛽ AÑADIR COMBUSTIBLE ($50)', 'crema.ignite': '🔥 ENCENDER',
'crema.no_money_fuel': '¡No hay dinero suficiente para combustible!',
'crema.fuel_full': '¡El depósito está lleno!',
'crema.already_burning': '¡Ya está encendido!', 'crema.add_fuel_first': '¡Añade combustible primero!',
'crema.ignited': '🔥 ¡Crematorio encendido! Subiendo temperatura...',
'crema.fuel_depleted': '🔥 ¡Combustible del crematorio agotado!',
'crema.cremating': '🔥 {0} se está incinerando... Tardará 1 hora.',
'crema.done_desc': 'La cremación de {0} ha finalizado.',
'crema.waiting': '🔥 La familia de {0} está esperando la cremación.',
'crema.btn_cremate': 'CREMAR', 'crema.need_800': '⏳ Necesita 800°C',
'crema.incinerating': '🔥 INCINERANDO...',
'crema.eff_perfect': '¡Perfecto!', 'crema.eff_heating': 'Calentando...', 'crema.eff_warming': 'Precalentando',
'crema.perfect_msg': '✨ ¡Cremación perfecta! Las cenizas de {0} son limpias y puras.',
'crema.decent_msg': '👍 Cremación decente. Quedan algunos fragmentos, pero aceptable.',
'crema.bad_msg': '😬 Cremación mala. Los resultados son... subóptimos. La familia no está contenta.',
// Viewing
'view.title': 'VELATORIO', 'view.subtitle': 'Un último adiós.',
'view.mood': '👨‍👩‍👧 ÁNIMO FAMILIAR', 'view.requests': '📋 PETICIONES',
'view.no_active': 'Sin velatorio activo',
'view.show_body': 'MOSTRAR CUERPO', 'view.water': 'TRAER AGUA', 'view.temp': 'AJUSTAR TEMP', 'view.firstaid': 'PRIMEROS AUX.',
'view.water_served': '💧 Agua servida. Los pequeños gestos importan.',
'view.temp_adjusted': '❄️ Temperatura ajustada. Mucho mejor.',
'view.no_ac': '⚠️ ¡Sin sistema de A/C! Cómpralo en Mejoras.',
'view.firstaid_done': '🩹 ¡Primeros auxilios administrados! ¡Crisis evitada!',
'view.no_firstaid': '⚠️ ¡Sin Kit de Primeros Auxilios! ¡Alguien sigue en el suelo!',
'view.glad_goodbye': 'Me alegra que pudierais despediros.',
'view.sorry': 'Yo... lo siento mucho.',
'view.body_title': '👁️ VELATORIO — {0}',
// Chapel
'chapel.title': 'LA CAPILLA', 'chapel.subtitle': 'Fe. Ritual. Consuelo.',
'chapel.ivan': 'Iván — El Orador', 'chapel.service': '🕯️ TIPO DE SERVICIO',
'chapel.no_service': 'Sin servicio programado', 'chapel.select_sermon': '📜 ELEGIR SERMÓN',
'chapel.comfort': 'CONFORT', 'chapel.begin': 'COMENZAR CEREMONIA',
'chapel.correct': 'Bella ceremonia, Iván.', 'chapel.wrong': 'Oh no...',
'chapel.ivan_speaks': '🎤 IVÁN HABLA',
'chapel.ceremony_for': 'Ceremonia para:', 'chapel.religion': 'Religión:',
// Office
'office.title': 'MEJORAS', 'office.subtitle': 'Invierte en la muerte.',
// Families
'fam.title': 'REGISTRO DE FAMILIAS', 'fam.subtitle': 'A quienes hemos servido.',
'fam.no_families': 'Sin familias aún. ¿La muerte se tomó un día libre?',
'fam.active': '● ACTIVA', 'fam.waiting': '● ESPERANDO COCHE', 'fam.completed': '✓ COMPLETADA',
'fam.rating': 'Valoración', 'fam.satisfaction': 'Satisfacción', 'fam.transport': 'Transporte',
'fam.services': 'Servicios', 'fam.earned': 'Ganado', 'fam.rep': 'Reputación',
'fam.cremated_onsite': '🔥 Cremado en el sitio', 'fam.hearse_transfer': '🚗 Trasladado en coche fúnebre',
'fam.embalmed': '✓ Embalsamado', 'fam.not_embalmed': '✗ No embalsamado',
'fam.viewing_done': '✓ Velatorio realizado', 'fam.chapel_service': '✓ Servicio de capilla',
'fam.cremation_done': '✓ Cremado', 'fam.basic_only': 'Solo básico',
'fam.departed': '☠ {0} — PARTIÓ',
'fam.service_complete': 'Todos los servicios para {0} están completos. Ve a Recepción y llama a un coche fúnebre.',
'fam.transfer_desc': '🚐 Trasladar a {0}',
// Game Over
'go.title': 'FIN DEL JUEGO', 'go.try_again': 'REINTENTAR',
'go.bankrupt_title': 'BANCARROTA', 'go.bankrupt_reason': 'Te quedaste sin dinero. Hasta la muerte cuesta dinero, por lo visto.',
'go.disgraced_title': 'DESHONRADO', 'go.disgraced_reason': 'Tu reputación tocó fondo. Nadie te confía a sus muertos.',
'go.money_warning': '⚠️ AVISO: ¡Dinero bajo! (${0})',
'go.rep_warning': '⚠️ AVISO: ¡Reputación peligrosamente baja!',
'go.days': 'Días sobrevividos:', 'go.served': 'Familias servidas:', 'go.earnings': 'Ganancias totales:',
'go.best_roll': 'Mejor tirada:', 'go.level': 'Nivel alcanzado:',
// Overlays
'ov.service_complete': '☠ SERVICIO COMPLETADO', 'ov.dismiss': 'CERRAR',
'ov.shop_title': '🛒 MERCADO DE SUMINISTROS', 'ov.shop_subtitle': 'Los precios fluctúan a diario. Compra con cabeza.',
'ov.shop_cancel': 'CANCELAR', 'ov.shop_buy': 'COMPRAR TODO',
'ov.shop_select': '¡Selecciona al menos un artículo!', 'ov.shop_no_money': '¡No hay suficiente dinero! Necesitas ${0}.',
'ov.shop_delivered': '📦 ¡Suministros entregados!',
'ov.credits_title': '♱ CRÉDITOS', 'ov.credits_game': 'Un juego sobre la muerte, el papeleo y el café horrible.',
'ov.credits_design': 'Diseño y Concepto: K. Arlón', 'ov.credits_ivan': 'Orador: Iván (él insistió)',
'ov.credits_quote': '"La vida es temporal. El papeleo es eterno."', 'ov.back': 'VOLVER',
'ov.roll': '¡TIRAR!',
// Engine
'eng.new_pw': '📝 Nuevo papeleo a las {0}',
'eng.end_title': '🛌 FIN DEL DÍA', 'eng.end_text': 'Parece que no quedan más tareas para hoy. ¿Quieres irte a dormir?',
'eng.end_yes': 'SÍ, A DORMIR', 'eng.end_no': 'TODAVÍA NO',
'eng.end_stay': 'Decidiste quedarte despierto un poco más.',
'eng.day_ended': '🌙 El día {0} terminó. Un nuevo día amanece en Descanso Eterno.',
'eng.daily_expenses': 'Gastos diarios (Día {0})',
'eng.level_up': '🎉 ¡SUBIDA DE NIVEL! ¡Ahora eres Nivel {0}!',
'eng.level_bonus': 'Bonus por Subir de Nivel',
'eng.need_level': '¡Necesitas Nivel {0}!', 'eng.not_enough': '¡No hay suficiente dinero!',
'eng.max_training': '¡Entrenamiento máximo alcanzado!',
'eng.arrival_desc': 'Nueva familia llegando a las {0}',
'eng.pw_desk': '¡Nuevo papeleo en tu escritorio!',
'eng.cremation_family': 'Una familia viene para un servicio de cremación.',
// Dialogue
'dlg.new_arrival': 'NUEVA LLEGADA', 'dlg.family_registered': '📋 FAMILIA REGISTRADA',
'dlg.deceased': 'Fallecido:', 'dlg.age': 'Edad:', 'dlg.sex': 'Sexo:',
'dlg.religion': 'Religión:', 'dlg.cause': 'Causa:', 'dlg.service': 'Servicio:',
'dlg.cremation': '🔥 Cremación', 'dlg.burial': '⚰️ Entierro',
'dlg.viewing_req': '👁️ Velatorio solicitado', 'dlg.chapel_req': '⛪ Servicio de capilla solicitado',
'dlg.understood': 'ENTENDIDO, PROCEDER',
// Dice
'dice.modifier': 'Modificador: {0}',
'dice.crit_fail': '💀 ¡FALLO CRÍTICO!', 'dice.catastrophic': '🔥 ¡Catastrófico!',
'dice.bad': '😬 Malo...', 'dice.mediocre': '😐 Mediocre',
'dice.good': '👍 ¡Bien!', 'dice.great': '✨ ¡Genial!', 'dice.crit_success': '💀✨ ¡ÉXITO CRÍTICO!',
'dice.result': 'Tirada {0} = {1} — {2}',
// Shop labels
'shop.formaldehyde': 'Formaldehído', 'shop.humectant': 'Humectante',
'shop.dye': 'Tinte Cosmético', 'shop.outfit': 'Traje Funerario',
'shop.in_stock': 'En stock: {0} {1}',
'shop.market_cheap': '📉 ¡Liquidación del proveedor! Precios bajos.',
'shop.market_normal': '📦 Condiciones normales de mercado.',
'shop.market_high': '📈 Alta demanda. Precios elevados.',
'shop.market_critical': '💀 ¡Escasez crítica! ¡Precios por las nubes!',
// Language
'lang.select': 'IDIOMA',
});
