/* ===== Spanish Strings ===== */
I18n.register('es', {
// Title
'splash.loading': 'Cargando gusanos...',
'title.tagline': 'Un RPG de Gestión Sobre la Vida en un Tanatorio',
'title.quote': '"No salvas vidas, ayudas a terminar con ellas... profesionalmente."',
'title.new_game': 'NUEVA PARTIDA', 'title.continue': 'CARGAR PARTIDA', 'title.resume': 'CONTINUAR', 'title.credits': 'CRÉDITOS',
'title.save': 'GUARDAR', 'title.exit': 'SALIR',
'title.exit_confirm': '¿Estás seguro de que quieres salir? Se perderá el progreso no guardado.',
'title.footer': 'DISEÑO Y CONCEPTO POR K. ARLÓN<br>COLOR DEL HUMOR: NEGRO — CLASIFICADO POR DEATH INC.',
'credits.title': '♱ CRÉDITOS',
'credits.desc': 'Un juego sobre la muerte, el papeleo y un café terrible.',
'credits.design': 'Diseño y Concepto: K. Arlón',
'credits.orator': 'Orador: Iván (insistió en salir aquí)',
'credits.quote': '"La vida es temporal. El papeleo es eterno."',
'credits.back': 'VOLVER',
// Name
'name.title': '¿QUIÉN SE ATREVE A DIRIGIR UN TANATORIO?',
'name.subtitle': 'Introduce tu nombre, futuro tanatopractor:',
'name.placeholder': 'Tu nombre...', 'name.begin': 'COMENZAR TU CARRERA',
'name.error': '¡Introduce un nombre! Hasta los muertos tienen nombre.',
'name.f1': '"Todo gran tanatopractor empezó en algún sitio."',
'name.f2': '"La muerte es solo el principio... de tu carrera."',
'name.f3': '"Tu madre debe estar muy orgullosa."',
'name.f4': '"Esperemos que lo escribas bien en las lápidas."',
'name.f5': '"Los muertos no pueden juzgar tu nombre. Los vivos sí."',
// Welcome
'welcome.title': 'BIENVENIDO A THANATOPRACTOR',
'welcome.p1': 'Aquí no salvamos vidas, solo las envolvemos con un lazo. Tu trabajo es simple: maquillar a los muertos para que parezcan vivos, quemarlos si la familia no quiere verlos más, y sobre todo, no aficionarse a la necrofilia.',
'welcome.p2': 'Al hacer clic abajo, aceptas que el formaldehído es tu nueva colonia favorita, que los fantasmas no pagan alquiler, y que no somos responsables de pesadillas recurrentes ni del tipo de humor con el que te vas a encontrar.',
'welcome.accept': 'ACEPTO LOS TÉRMINOS',
// Hub
'hub.day': 'DÍA', 'hub.reputation': 'REPUTACIÓN', 'hub.schedule': 'AGENDA DE HOY',
'hub.eternal_rest': 'TANATORIO', 'hub.funeral_house': 'DESCANSO ETERNO',
'hub.motto': '"Cuidamos de ellos hasta el final"',
'hub.no_appointments': 'No hay citas para hoy.',
'hub.locked': '🔒 ¡Compra esta sala en el menú de Mejoras!',
'hub.welcome': '☠ Bienvenido, {0}. Los muertos te esperan.',
// Nav
'nav.reception': 'Recepción', 'nav.embalming': 'Embalsamar', 'nav.cafeteria': 'Cafetería',
'nav.crematorium': 'Cremat.', 'nav.viewing': 'Velatorio', 'nav.chapel': 'Capilla',
'nav.upgrades': 'Mejoras', 'nav.families': 'Familias',
// Reception
'rec.title': 'RECEPCIÓN', 'rec.new_arrival': 'NUEVA LLEGADA', 'rec.phone': 'LLAMAR',
'rec.paperwork': 'PAPELEO', 'rec.upgrades': 'MEJORAS',
'rec.appointments': 'CITAS DE HOY', 'rec.no_appointments': 'Sin citas hoy',
'rec.no_waiting': 'No hay familias esperando ahora mismo.',
'rec.phone_title': '📞 MENÚ TELEFÓNICO', 'rec.phone_subtitle': '¿A quién quieres llamar hoy?',
'rec.job_interview': 'Entrevista de trabajo ($50)',
'rec.job_result': 'Llamaste a un candidato. Escuchas gritos de fondo y cuelgan.',
'rec.order_hearse': 'Pedir Coche Fúnebre ($150)',
'rec.hearse_ordered': 'Coche fúnebre pedido. El conductor dice que llegará "eventualmente".',
'rec.hearse_multi': 'Coche(s) fúnebre(s) pedido(s). Llegará(n) en 1 hora.',
'rec.need_money_hearse': '¡Necesitas ${0} para {1} coches fúnebres!',
'rec.order_flowers': 'Pedir Flores ($50)',
'rec.flowers_result': '¡Flores frescas entregadas! El velatorio huele un poco menos a formaldehído.',
'rec.nevermind': 'Nada, déjalo',
'rec.personal_hearse': '🚗 Usar Coche Fúnebre Personal (Gratis)',
'rec.niece_car': '🚗 Usar Coche de la Sobrina (Gratis)',
'rec.car_cooldown': '🚗 Coche en enfriamiento ({0}h)',
'rec.car_dispatched': '🚗 Coche enviado para {0}. Estará fuera {1}h.',
'rec.niece_arrived': '🚗 ¡Tu sobrina ha llegado al instante! La familia de {0} se ha marchado.',
'rec.car_busy': '¡El coche está haciendo un traslado ahora mismo!',
'rec.no_family_transport': 'No hay familias esperando transporte.',
'rec.no_paperwork': '📝 Sin papeleo ahora mismo. Disfruta del silencio.',
'rec.pw_title': '📝 PAPELEO', 'rec.pw_roll': 'Tirar D20',
'rec.pw_success': '¡Éxito! Has ganado ${0}.', 'rec.pw_fail': '¡Fallo! Has perdido ${0}.',
'rec.pw_discarded': '📝 Papeleo descartado.', 'rec.pw_decline': '(Rechazar)',
'rec.hearse_picking': 'El coche fúnebre recoge a la familia de {0}.',
'rec.car_ordered': '📦 (Coche pedido en camino) - {0}',
// Embalming
'emb.title': 'SALA DE EMBALSAMAR', 'emb.subtitle': 'Preservar la dignidad.',
'emb.no_body': 'Sin cuerpo que preparar', 'emb.preparing': 'Preparando: {0}',
'emb.tasks': 'TAREAS', 'emb.clean': 'Limpiar', 'emb.treat': 'Tratar', 'emb.dress': 'Vestir', 'emb.prepare': 'Preparar',
'emb.supplies': 'SUMINISTROS', 'emb.quality': 'CALIDAD',
'emb.buy': '🛒 COMPRAR SUMINISTROS', 'emb.roll': '¡TIRAR D20 — EMBALSAMAR!',
'emb.no_chemicals': '⚠️ ¡No hay suficientes químicos!', 'emb.no_outfits': '⚠️ ¡No quedan trajes!',
'emb.finish': '🎲 FINALIZAR Y TIRAR {0}',
'emb.q_catastrophic': '💀 Oh no. {0} parece una figura de cera encantada. Esto NO va a acabar bien.',
'emb.q_bad': '😬 {0} se ve... raro. Como si te juzgara desde el más allá.',
'emb.q_mediocre': '😐 {0} se ve aceptable. Ni bien ni mal. Como un 5 raspao.',
'emb.q_good': '👍 {0} se ve en paz. ¡Buen trabajo!',
'emb.q_excellent': '✨ {0} se ve mejor muerto que la mayoría de la gente viva. ¡Obra maestra!',
'emb.needs_embalming': '🧪 ¡{0} necesita embalsamamiento!',
'emb.still_needs': '🧪 ¡{0} todavía necesita embalsamamiento!',
'emb.penalty': '({0} Penalización)', 'emb.no_penalty': '(SIN PENALIZACIÓN)',
// Tutorial embalsamar
'emb.tutorial_title': '🧪 PRIMERA VEZ EN LA SALA DE EMBALSAMAR',
'emb.tutorial_text': 'Acuérdate de tener los suministros al día, tardan una hora en llegar. Quedarte sin material a mitad de procedimiento es... incómodo.',
'emb.tutorial_ok': 'Entendido, comprar con antelación',
// Cafeteria
'cafe.title': 'CAFETERÍA', 'cafe.subtitle': 'También para los vivos.',
'cafe.menu': '☕ MENÚ MORTALMENTE BUENO', 'cafe.orders': '📝 PEDIDOS',
'cafe.satisfaction': '😊 SATISFACCIÓN', 'cafe.no_orders': 'Sin pedidos activos ahora mismo.',
'cafe.no_orders_yet': 'Sin pedidos aún', 'cafe.served': 'Servido',
'cafe.alcohol_title': '🍺 PETICIÓN DE ALCOHOL', 'cafe.alcohol_request': 'Petición de alcohol',
// Crematorium
'crema.title': 'CREMATORIO', 'crema.subtitle': 'Reducción a lo esencial.',
'crema.temp': '🌡️ TEMPERATURA', 'crema.fuel': '⛽ COMBUSTIBLE', 'crema.efficiency': '📊 EFICIENCIA',
'crema.schedule': 'AGENDA DE HOY', 'crema.no_scheduled': 'Sin cremaciones programadas',
'crema.add_fuel': '⛽ AÑADIR COMBUSTIBLE ($50)', 'crema.ignite': '🔥 ENCENDER',
'crema.no_money_fuel': '¡No hay dinero suficiente para combustible!',
'crema.fuel_full': '¡El depósito está lleno!',
'crema.already_burning': '¡Ya está encendido!', 'crema.add_fuel_first': '¡Añade combustible primero!',
'crema.ignited': '🔥 ¡Crematorio encendido! Subiendo temperatura...',
'crema.fuel_depleted': '🔥 ¡Combustible del crematorio agotado!',
'crema.cremating': '🔥 {0} se está incinerando... Tardará 1 hora.',
'crema.done_desc': 'La cremación de {0} ha finalizado.',
'crema.waiting': '🔥 La familia de {0} está esperando la cremación.',
'crema.btn_cremate': 'CREMAR', 'crema.need_800': '⏳ Necesita 800°C',
'crema.incinerating': '🔥 INCINERANDO...',
'crema.eff_perfect': '¡Perfecto!', 'crema.eff_heating': 'Calentando...', 'crema.eff_warming': 'Precalentando',
'crema.perfect_msg': '✨ ¡Cremación perfecta! Las cenizas de {0} son limpias y puras.',
'crema.decent_msg': '👍 Cremación decente. Quedan algunos fragmentos, pero aceptable.',
'crema.bad_msg': '😬 Cremación mala. Los resultados son... subóptimos. La familia no está contenta.',
// Tutorial crematorio
'crema.tutorial_title': '🔥 PRIMERA VEZ EN EL CREMATORIO',
'crema.tutorial_text': 'El horno tarda en calentar. Una vez iniciada la cremación, tiene que permanecer encendido 1 hora para hacer unas buenas cenizas. Si la temperatura baja de 700°C durante el proceso... digamos que la familia no estará contenta.',
'crema.tutorial_ok': 'Entendido, mantener el fuego',
// Viewing
'view.title': 'VELATORIO', 'view.subtitle': 'Un último adiós.',
'view.mood': '👨‍👩‍👧 ÁNIMO FAMILIAR', 'view.requests': '📋 PETICIONES',
'view.no_active': 'Sin velatorio activo',
'view.show_body': 'MOSTRAR CUERPO', 'view.water': 'TRAER AGUA', 'view.temp': 'AJUSTAR TEMP', 'view.firstaid': 'PRIMEROS AUX.',
'view.water_served': '💧 Agua servida. Los pequeños gestos importan.',
'view.temp_adjusted': '❄️ Temperatura ajustada. Mucho mejor.',
'view.no_ac': '⚠️ ¡Sin sistema de A/C! Cómpralo en Mejoras.',
'view.firstaid_done': '🩹 ¡Primeros auxilios administrados! ¡Crisis evitada!',
'view.no_firstaid': '⚠️ ¡Sin Kit de Primeros Auxilios! ¡Alguien sigue en el suelo!',
'view.all_fulfilled': 'Todas las peticiones atendidas.',
'view.already_seen': 'Ya han visto el cuerpo.',
'view.no_water_needed': 'No tienen sed ahora mismo.',
'view.no_temp_needed': 'Están cómodos con la temperatura.',
'view.no_firstaid_needed': 'Nadie necesita primeros auxilios.',
'view.sorry': 'Lo siento mucho...',
'view.glad_goodbye': 'Adiós, descansa en paz.',
// Tutorial velatorio
'view.tutorial_title': '👁️ PRIMERA VEZ EN EL VELATORIO',
'view.tutorial_text': 'Las familias pueden pedir de todo. Ten todo listo para ganar reputación. Familias contentas significan mejores valoraciones.',
'view.tutorial_ok': 'Entendido, estar preparado',
// Chapel
'chapel.title': 'LA CAPILLA', 'chapel.subtitle': 'Fe. Ritual. Consuelo.',
'chapel.ivan': 'Iván — El Orador', 'chapel.service': '🕯️ TIPO DE SERVICIO',
'chapel.no_service': 'Sin servicio programado', 'chapel.select_sermon': '📜 ELEGIR SERMÓN',
'chapel.comfort': 'CONFORT', 'chapel.begin': 'COMENZAR CEREMONIA',
'chapel.correct': 'Bella ceremonia, Iván.', 'chapel.wrong': 'Oh no...',
'chapel.ivan_speaks': '🎤 IVÁN HABLA',
'chapel.ceremony_for': 'Ceremonia para:', 'chapel.religion': 'Religión:',
'chapel.waiting_toast': '🎤 ¡{0} está esperando para la ceremonia en la Capilla!',
// Tutorial capilla
'chapel.tutorial_title': '⛪ PRIMERA VEZ EN LA CAPILLA',
'chapel.tutorial_text': 'Asegúrate de la creencia religiosa de la familia en el menú Familias, antes de abrir el pico. Elegir el sermón equivocado puede ser... catastrófico.',
'chapel.tutorial_ok': 'Entendido, miraré primero',
// Violín
'chapel.violin_offer_title': '🎻 ACOMPAÑAMIENTO MUSICAL',
'chapel.violin_offer_text': 'La legendaria, incomparable, devastadoramente talentosa violinista Aida está disponible hoy. ¿Quieres ofrecer a la familia una actuación de violín en directo durante la ceremonia? (Coste para la familia: $40)',
'chapel.violin_offer_yes': 'Ofrecer música de violín ($40)',
'chapel.violin_offer_no': 'Pasar de la música',
'chapel.violin_accept_title': '🎻 AIDA ACTÚA',
'chapel.violin_decline_title': '🎻 MÚSICA RECHAZADA',
'chapel.violin_income': 'Actuación de violín por Aida',
'chapel.violin_bravo': '¡Bravo, Aida!',
'chapel.violin_ok': 'Pues vale.',
'chapel.aida_quote_1': 'Aida, la prodigiosa, la sublime, la única violinista que una vez hizo llorar a una estatua, toca una melodía tan bella que hasta el difunto parece sonreír. Varios familiares lloran. Uno lo está grabando con el móvil.',
'chapel.aida_quote_2': 'Aida, virtuosa extraordinaria y autoproclamada "ángel de las cuerdas", comienza un delicado adagio. Una mosca en la capilla se detiene en el aire para escuchar. Verdaderamente, es un regalo para el reino mortal.',
'chapel.aida_quote_3': 'Aida, cuyo talento ha sido descrito como "alarmante" por al menos tres orquestas, interpreta una pieza desgarradoramente bella. La familia está profundamente conmovida. Alguien susurra: "¿Puede tocar en MI funeral también?"',
'chapel.aida_quote_4': 'La magnífica Aida, que asegura haber estudiado bajo la tutela de un fantasma en Viena, llena la capilla con notas tan puras que podrían resucitar a los muertos. No lo hacen, claro. Eso sería un problema de responsabilidad civil.',
'chapel.aida_quote_5': 'Aida, leyenda de las cuerdas, de quien se rumorea que afina su violín con lágrimas de alegría, toca una pieza que hace que todos olviden que están en un tanatorio. Durante unos 4 minutos, al menos.',
'chapel.violin_reject_1': 'La familia declina educadamente. "Gracias, pero el tío Jorge siempre decía que los violines sonaban como gatos enfadados." Pues vale.',
'chapel.violin_reject_2': 'La familia dice que no. "Lo agradecemos, pero el difunto pidió específicamente silencio. Y un kazoo, pero esa parte la estamos ignorando."',
'chapel.violin_reject_3': '"No, gracias. La última vez que hubo música en directo en un funeral, la abuela se puso a bailar. Y no era la difunta."',
// Office
'office.title': 'MEJORAS', 'office.subtitle': 'Invierte en la muerte.',
// Families
'fam.title': 'REGISTRO DE FAMILIAS', 'fam.subtitle': 'A quienes hemos servido.',
'fam.no_families': 'Sin familias aún. ¿La muerte se tomó un día libre?',
'fam.active': '● ACTIVA', 'fam.waiting': '● ESPERANDO COCHE', 'fam.completed': '✓ COMPLETADA',
'fam.rating': 'Valoración', 'fam.satisfaction': 'Satisfacción', 'fam.transport': 'Transporte',
'fam.services': 'Servicios', 'fam.earned': 'Ganado', 'fam.rep': 'Reputación',
'fam.cremated_onsite': '🔥 Cremado en el sitio', 'fam.hearse_transfer': '🚗 Trasladado en coche fúnebre',
'fam.embalmed': '✓ Embalsamado', 'fam.not_embalmed': '✗ No embalsamado',
'fam.viewing_done': '✓ Velatorio realizado', 'fam.chapel_service': '✓ Servicio de capilla',
'fam.cremation_done': '✓ Cremado', 'fam.basic_only': 'Solo básico',
'fam.departed': '☠ {0} — PARTIÓ',
'fam.service_complete': 'Todos los servicios para {0} están completos. Ve a Recepción y llama a un coche fúnebre.',
'fam.transfer_desc': '🚐 Trasladar a {0}',
// Game Over
'go.title': 'FIN DEL JUEGO', 'go.try_again': 'REINTENTAR',
'go.bankrupt_title': 'BANCARROTA', 'go.bankrupt_reason': 'Te quedaste sin dinero. Hasta la muerte cuesta dinero, por lo visto.',
'go.disgraced_title': 'DESHONRADO', 'go.disgraced_reason': 'Tu reputación tocó fondo. Nadie te confía a sus muertos.',
'go.money_warning': '⚠️ AVISO: ¡Dinero bajo! (${0})',
'go.rep_warning': '⚠️ AVISO: ¡Reputación peligrosamente baja!',
'go.days': 'Días sobrevividos:', 'go.served': 'Familias servidas:', 'go.earnings': 'Ganancias totales:',
'go.best_roll': 'Mejor tirada:', 'go.level': 'Nivel alcanzado:',
// Overlays
'ov.service_complete': '☠ SERVICIO COMPLETADO',
'ov.summary_deceased': 'Difunto',
'ov.summary_rating': 'Valoración',
'ov.summary_satisfaction': 'Satisfacción',
'ov.summary_transport': 'Transporte',
'ov.summary_services': 'Servicios',
'ov.summary_earned': 'Ganado',
'ov.summary_reputation': 'Reputación',
'ov.summary_departed': 'HA PARTIDO',
'ov.saved': '💾 ¡PROGRESO GUARDADO!',
'ov.summary_basic': 'Solo básico',
'ov.summary_ordered': 'Pedido',
'ov.summary_cremated': 'Incinerado',
'ov.summary_chapel': 'Capilla',
'ov.summary_flowers': 'Flores',
'ov.summary_viewing': 'Velatorio',
'ov.summary_embalmed': 'Embalsamado',
'ov.summary_not_embalmed': 'Sin embalsamar',
'ov.summary_cremated_onsite': '🔥 Incinerado aquí',
'ov.summary_hearse_transfer': '🚗 Trasladado en coche fúnebre',
'ov.status_waiting': '● ESPERANDO COCHE',
'ov.status_active': '● ACTIVO',
'ov.status_completed': '✓ COMPLETADO',
'ov.no_families': 'No hay familias aún. ¿La muerte se ha tomado el día libre?',
'ov.dismiss': 'CERRAR',
'ov.shop_title': '🛒 MERCADO DE SUMINISTROS',
'ov.shop_subtitle': 'Los precios fluctúan a diario. Compra con cabeza.',
'ov.shop_cancel': 'CANCELAR',
'ov.shop_buy': 'COMPRAR',
'ov.shop_select': '¡Selecciona al menos un artículo!', 'ov.shop_no_money': '¡No hay suficiente dinero! Necesitas ${0}.',
'ov.shop_delivered': '📦 ¡Suministros entregados!',
'shop.mood_clearance': '📉 ¡Liquidación del proveedor! Precios bajos.',
'shop.mood_normal': '📦 Condiciones normales de mercado.',
'shop.mood_high': '📈 Alta demanda. Precios elevados.',
'shop.mood_shortage': '💀 ¡Escasez crítica! ¡Precios por las nubes!',
'shop.in_stock': 'En stock: {0} {1}',
'shop.ea': 'u',
'shop.select_item': '¡Selecciona al menos un artículo!',
'shop.no_money': '¡No hay suficiente dinero! Necesitas ${0}.',
'shop.delivery_desc': '📦 Entrega de suministros',
'shop.delivered': '📦 Suministros pedidos. Entrega en 1h.',
'ov.credits_title': '♱ CRÉDITOS', 'ov.credits_game': 'Un juego sobre la muerte, el papeleo y el café horrible.',
'ov.credits_design': 'Diseño y Concepto: K. Arlón', 'ov.credits_ivan': 'Orador: Iván (él insistió)',
'ov.credits_quote': '"La vida es temporal. El papeleo es eterno."', 'ov.back': 'VOLVER',
'ov.roll': '¡TIRAR!',
// Engine
'eng.new_pw': '📝 Nuevo papeleo a las {0}',
'eng.end_title': '🛌 FIN DEL DÍA', 'eng.end_text': 'Parece que no quedan más tareas para hoy. ¿Quieres irte a dormir?',
'eng.end_yes': 'SÍ, A DORMIR', 'eng.end_no': 'TODAVÍA NO',
'eng.end_stay': 'Decidiste quedarte despierto un poco más.',
'eng.day_ended': '🌙 El día {0} terminó. Un nuevo día amanece en Descanso Eterno.',
'eng.daily_expenses': 'Gastos diarios (Día {0})',
'eng.level_up': '🎉 ¡SUBIDA DE NIVEL! ¡Ahora eres Nivel {0}!',
'eng.level_bonus': 'Bonus por Subir de Nivel',
'eng.need_level': '¡Necesitas Nivel {0}!', 'eng.not_enough': '¡No hay suficiente dinero!',
'eng.max_training': '¡Entrenamiento máximo alcanzado!',
'eng.arrival_desc': 'Nueva familia llegando a las {0}',
'eng.pw_desk': '¡Nuevo papeleo en tu escritorio!',
'eng.cremation_family': 'Una familia viene para un servicio de cremación.',
// Dialogue
'dlg.new_arrival': 'NUEVA LLEGADA', 'dlg.family_registered': '📋 FAMILIA REGISTRADA',
'dlg.deceased': 'Fallecido:', 'dlg.age': 'Edad:', 'dlg.sex': 'Sexo:',
'dlg.religion': 'Religión:', 'dlg.cause': 'Causa:', 'dlg.service': 'Servicio:',
'dlg.cremation': '🔥 Cremación', 'dlg.burial': '⚰️ Entierro',
'dlg.viewing_req': '👁️ Velatorio solicitado', 'dlg.chapel_req': '⛪ Servicio de capilla solicitado',
'dlg.understood': 'ENTENDIDO, PROCEDER',
// Dice
'dice.modifier': 'Modificador: {0}',
'dice.crit_fail': '💀 ¡FALLO CRÍTICO!', 'dice.catastrophic': '🔥 ¡Catastrófico!',
'dice.bad': '😬 Malo...', 'dice.mediocre': '😐 Mediocre',
'dice.good': '👍 ¡Bien!', 'dice.great': '✨ ¡Genial!', 'dice.crit_success': '💀✨ ¡ÉXITO CRÍTICO!',
'dice.result': 'Tirada {0} = {1} — {2}',
// Shop labels
'shop.formaldehyde': 'Formaldehído', 'shop.humectant': 'Humectante',
'shop.dye': 'Tinte Cosmético', 'shop.outfit': 'Traje Funerario',
'shop.in_stock': 'En stock: {0} {1}',
'shop.market_cheap': '📉 ¡Liquidación del proveedor! Precios bajos.',
'shop.market_normal': '📦 Condiciones normales de mercado.',
'shop.market_high': '📈 Alta demanda. Precios elevados.',
'shop.market_critical': '💀 ¡Escasez crítica! ¡Precios por las nubes!',
// Language
'shop.vials': 'viales', 'shop.jars': 'tarros', 'shop.tubes': 'tubos', 'shop.sets': 'conjuntos',
'rec.pw_dc': 'Dificultad (DC): {0}',
'rec.personal_enroute': '🚗 (Coche personal en camino) - {0}',
'rec.personal_pickup': 'El coche personal está recogiendo a {0}.',
'off.trained': 'Entrenado: {0}/{1}',
'crema.done_desc': 'Incineración de {0} terminada.',
'crema.need_800': 'Esperar a 800°C',
'crema.incinerating': '🔥 Incinerando...',
'crema.btn_cremate': '🔥 INCINERAR',
'rec.niece_desc': '🚗 Tu sobrina puede llevarse un cuerpo gratis.',
'crema.ready_desc': '{0} está listo para la incineración.',
'rec.arrival_pickup': 'La familia de {0} ha llegado para la recogida.',
'cafe.inspector_title': '🚨 INSPECTOR DE SANIDAD',
'cafe.inspector_msg': '¡Alto ahí! Soy un inspector secreto de sanidad. Se le ha pillado sirviendo alcohol ilegal varias veces hoy. ¡Este establecimiento queda cerrado hasta nuevo aviso!',
'cafe.inspector_ok': 'ENTENDIDO',
'dlg.male': 'Hombre', 'dlg.female': 'Mujer',
'dlg.needs_embalming': '🧪 ¡{0} necesita ser embalsamado!',
'dlg.family_title': "Familia de {0}",
'emb.catastrophic': '🔥 ¡DESASTRE! La familia quedará horrorizada.',
'emb.bad': '😬 Mal resultado. Esto dañará tu reputación.',
'emb.mediocre': '😐 Trabajo mediocre. Podría estar mejor.',
'emb.good': '👍 Buen trabajo. La familia estará satisfecha.',
'emb.excellent': '✨ ¡Obra maestra! Eres un verdadero artista de la muerte.',
'rec.services_complete': 'Todos los servicios para {0} han terminado. Ve a Recepción y llama al coche fúnebre.',
'crema.waiting_toast': '🔥 ¡{0} está esperando para la incineración!',
'emb.quality_title': 'Calidad del embalsamamiento: {0}',
'dlg.random_event': '📢 EVENTO ALEATORIO',
'rec.transfer_ready': '🚐 Transferir a {0}',
'eng.alert_18_title': '¡ALERTA!',
'eng.alert_18_msg': '¡Rápido, termina todas tus tareas, el tanatorio cierra en 2 horas!',
});
