plugins {
    id 'com.android.application'
}

android {
    namespace 'com.thanato.practor'
    compileSdk 36

    defaultConfig {
        applicationId "com.thanato.practor"
        minSdk 24
        targetSdk 36
        versionCode 4
        versionName "1.4"
    }

    signingConfigs {
        release {
            storeFile file("release-key.keystore")
            storePassword "android"
            keyAlias "my-key-alias"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.release
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}

dependencies {
    // Pure Android framework app, no external dependencies needed
}
